// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.17.0
// source: github.com/paralin/modlock/proto/modlock/camera.proto

package modlock_types

import (
	fmt "fmt"
	io "io"
	math "math"
	slices "slices"
	strconv "strconv"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
)

// Interpolation selects how values move between authored keys.
type Interpolation int32

const (
	// INTERPOLATION_UNSPECIFIED is the unspecified interpolation.
	Interpolation_INTERPOLATION_UNSPECIFIED Interpolation = 0
	// INTERPOLATION_LINEAR moves at a constant rate between keys.
	Interpolation_INTERPOLATION_LINEAR Interpolation = 1
	// INTERPOLATION_SMOOTH uses shape-preserving cubic Hermite between keys.
	Interpolation_INTERPOLATION_SMOOTH Interpolation = 2
	// INTERPOLATION_STEP holds the previous key's value until the next key.
	Interpolation_INTERPOLATION_STEP Interpolation = 3
)

// Enum value maps for Interpolation.
var (
	Interpolation_name = map[int32]string{
		0: "INTERPOLATION_UNSPECIFIED",
		1: "INTERPOLATION_LINEAR",
		2: "INTERPOLATION_SMOOTH",
		3: "INTERPOLATION_STEP",
	}
	Interpolation_value = map[string]int32{
		"INTERPOLATION_UNSPECIFIED": 0,
		"INTERPOLATION_LINEAR":      1,
		"INTERPOLATION_SMOOTH":      2,
		"INTERPOLATION_STEP":        3,
	}
)

func (x Interpolation) Enum() *Interpolation {
	p := new(Interpolation)
	*p = x
	return p
}

func (x Interpolation) String() string {
	name, valid := Interpolation_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// RotationMode selects how yaw and roll cross the 180-degree seam.
type RotationMode int32

const (
	// ROTATION_MODE_UNSPECIFIED is the unspecified rotation mode.
	RotationMode_ROTATION_MODE_UNSPECIFIED RotationMode = 0
	// ROTATION_MODE_SHORTEST travels the shorter arc between keys.
	RotationMode_ROTATION_MODE_SHORTEST RotationMode = 1
	// ROTATION_MODE_UNWRAPPED preserves authored full turns.
	RotationMode_ROTATION_MODE_UNWRAPPED RotationMode = 2
)

// Enum value maps for RotationMode.
var (
	RotationMode_name = map[int32]string{
		0: "ROTATION_MODE_UNSPECIFIED",
		1: "ROTATION_MODE_SHORTEST",
		2: "ROTATION_MODE_UNWRAPPED",
	}
	RotationMode_value = map[string]int32{
		"ROTATION_MODE_UNSPECIFIED": 0,
		"ROTATION_MODE_SHORTEST":    1,
		"ROTATION_MODE_UNWRAPPED":   2,
	}
)

func (x RotationMode) Enum() *RotationMode {
	p := new(RotationMode)
	*p = x
	return p
}

func (x RotationMode) String() string {
	name, valid := RotationMode_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// CameraPose is one evaluated camera state: position, orientation, and
// framing at one instant.
type CameraPose struct {
	unknownFields []byte
	// Position is the world-space camera position.
	Position *Vec3 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	// Angles is the camera orientation in degrees.
	Angles *EulerAngles `protobuf:"bytes,2,opt,name=angles,proto3" json:"angles,omitempty"`
	// AspectRatio is the framing ratio at this instant.
	AspectRatio float64 `protobuf:"fixed64,3,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspectRatio,omitempty"`
}

func (x *CameraPose) Reset() {
	*x = CameraPose{}
}

func (*CameraPose) ProtoMessage() {}

func (x *CameraPose) GetPosition() *Vec3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CameraPose) GetAngles() *EulerAngles {
	if x != nil {
		return x.Angles
	}
	return nil
}

func (x *CameraPose) GetAspectRatio() float64 {
	if x != nil {
		return x.AspectRatio
	}
	return 0
}

// CameraKeyframe is one authored camera pose at a shot-relative time.
type CameraKeyframe struct {
	unknownFields []byte
	// Time is the shot-relative second of this key; keys are strictly
	// increasing and nonnegative.
	Time float64 `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	// Position is the world-space camera position.
	Position *Vec3 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	// Angles is the camera orientation in degrees.
	Angles *EulerAngles `protobuf:"bytes,3,opt,name=angles,proto3" json:"angles,omitempty"`
	// AspectRatio is the authored framing ratio at this key.
	AspectRatio float64 `protobuf:"fixed64,4,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspectRatio,omitempty"`
}

func (x *CameraKeyframe) Reset() {
	*x = CameraKeyframe{}
}

func (*CameraKeyframe) ProtoMessage() {}

func (x *CameraKeyframe) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CameraKeyframe) GetPosition() *Vec3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CameraKeyframe) GetAngles() *EulerAngles {
	if x != nil {
		return x.Angles
	}
	return nil
}

func (x *CameraKeyframe) GetAspectRatio() float64 {
	if x != nil {
		return x.AspectRatio
	}
	return 0
}

// CameraPath is an authored, validated camera path. Evaluation is
// deterministic and stateless: forward playback and rewinds are identical.
type CameraPath struct {
	unknownFields []byte
	// Keys are the authored camera keyframes in strictly increasing time order.
	Keys []*CameraKeyframe `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// Interpolation selects movement between keys for position and angles.
	Interpolation Interpolation `protobuf:"varint,2,opt,name=interpolation,proto3" json:"interpolation,omitempty"`
	// RotationMode selects yaw and roll seam handling.
	RotationMode RotationMode `protobuf:"varint,3,opt,name=rotation_mode,json=rotationMode,proto3" json:"rotationMode,omitempty"`
	// LensInterpolation selects movement for the aspect-ratio channel.
	LensInterpolation Interpolation `protobuf:"varint,4,opt,name=lens_interpolation,json=lensInterpolation,proto3" json:"lensInterpolation,omitempty"`
}

func (x *CameraPath) Reset() {
	*x = CameraPath{}
}

func (*CameraPath) ProtoMessage() {}

func (x *CameraPath) GetKeys() []*CameraKeyframe {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CameraPath) GetInterpolation() Interpolation {
	if x != nil {
		return x.Interpolation
	}
	return Interpolation_INTERPOLATION_UNSPECIFIED
}

func (x *CameraPath) GetRotationMode() RotationMode {
	if x != nil {
		return x.RotationMode
	}
	return RotationMode_ROTATION_MODE_UNSPECIFIED
}

func (x *CameraPath) GetLensInterpolation() Interpolation {
	if x != nil {
		return x.LensInterpolation
	}
	return Interpolation_INTERPOLATION_UNSPECIFIED
}

func (m *CameraPose) CloneVT() *CameraPose {
	if m == nil {
		return (*CameraPose)(nil)
	}
	r := new(CameraPose)
	r.AspectRatio = m.AspectRatio
	r.Position = protobuf_go_lite.CloneVTValue(m.Position)
	r.Angles = protobuf_go_lite.CloneVTValue(m.Angles)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CameraPose) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CameraKeyframe) CloneVT() *CameraKeyframe {
	if m == nil {
		return (*CameraKeyframe)(nil)
	}
	r := new(CameraKeyframe)
	r.Time = m.Time
	r.AspectRatio = m.AspectRatio
	r.Position = protobuf_go_lite.CloneVTValue(m.Position)
	r.Angles = protobuf_go_lite.CloneVTValue(m.Angles)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CameraKeyframe) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CameraPath) CloneVT() *CameraPath {
	if m == nil {
		return (*CameraPath)(nil)
	}
	r := new(CameraPath)
	r.Interpolation = m.Interpolation
	r.RotationMode = m.RotationMode
	r.LensInterpolation = m.LensInterpolation
	r.Keys = protobuf_go_lite.CloneVTSlice(m.Keys)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CameraPath) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *CameraPose) EqualVT(that *CameraPose) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Position, that.Position) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Angles, that.Angles) {
		return false
	}
	if this.AspectRatio != that.AspectRatio {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CameraPose) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CameraPose)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CameraKeyframe) EqualVT(that *CameraKeyframe) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Time != that.Time {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Position, that.Position) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Angles, that.Angles) {
		return false
	}
	if this.AspectRatio != that.AspectRatio {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CameraKeyframe) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CameraKeyframe)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CameraPath) EqualVT(that *CameraPath) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Keys, that.Keys, func() *CameraKeyframe { return &CameraKeyframe{} }) {
		return false
	}
	if this.Interpolation != that.Interpolation {
		return false
	}
	if this.RotationMode != that.RotationMode {
		return false
	}
	if this.LensInterpolation != that.LensInterpolation {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CameraPath) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CameraPath)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the Interpolation to JSON.
func (x Interpolation) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), Interpolation_name)
}

// MarshalText marshals the Interpolation to text.
func (x Interpolation) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), Interpolation_name)), nil
}

// MarshalJSON marshals the Interpolation to JSON.
func (x Interpolation) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Interpolation from JSON.
func (x *Interpolation) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(Interpolation_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read Interpolation enum: %v", err)
		return
	}
	*x = Interpolation(v)
}

// UnmarshalText unmarshals the Interpolation from text.
func (x *Interpolation) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), Interpolation_value)
	if err != nil {
		return err
	}
	*x = Interpolation(i)
	return nil
}

// UnmarshalJSON unmarshals the Interpolation from JSON.
func (x *Interpolation) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the RotationMode to JSON.
func (x RotationMode) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), RotationMode_name)
}

// MarshalText marshals the RotationMode to text.
func (x RotationMode) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), RotationMode_name)), nil
}

// MarshalJSON marshals the RotationMode to JSON.
func (x RotationMode) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the RotationMode from JSON.
func (x *RotationMode) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(RotationMode_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read RotationMode enum: %v", err)
		return
	}
	*x = RotationMode(v)
}

// UnmarshalText unmarshals the RotationMode from text.
func (x *RotationMode) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), RotationMode_value)
	if err != nil {
		return err
	}
	*x = RotationMode(i)
	return nil
}

// UnmarshalJSON unmarshals the RotationMode from JSON.
func (x *RotationMode) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the CameraPose message to JSON.
func (x *CameraPose) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Position != nil || s.HasField("position") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("position")
		x.Position.MarshalProtoJSON(s.WithField("position"))
	}
	if x.Angles != nil || s.HasField("angles") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("angles")
		x.Angles.MarshalProtoJSON(s.WithField("angles"))
	}
	if x.AspectRatio != 0 || s.HasField("aspectRatio") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("aspectRatio")
		s.WriteFloat64(x.AspectRatio)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the CameraPose to JSON.
func (x *CameraPose) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the CameraPose message from JSON.
func (x *CameraPose) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "position":
			if s.ReadNil() {
				x.Position = nil
				return
			}
			x.Position = &Vec3{}
			x.Position.UnmarshalProtoJSON(s.WithField("position", true))
		case "angles":
			if s.ReadNil() {
				x.Angles = nil
				return
			}
			x.Angles = &EulerAngles{}
			x.Angles.UnmarshalProtoJSON(s.WithField("angles", true))
		case "aspect_ratio", "aspectRatio":
			s.AddField("aspect_ratio")
			x.AspectRatio = s.ReadFloat64()
		}
	})
}

// UnmarshalJSON unmarshals the CameraPose from JSON.
func (x *CameraPose) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the CameraKeyframe message to JSON.
func (x *CameraKeyframe) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Time != 0 || s.HasField("time") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("time")
		s.WriteFloat64(x.Time)
	}
	if x.Position != nil || s.HasField("position") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("position")
		x.Position.MarshalProtoJSON(s.WithField("position"))
	}
	if x.Angles != nil || s.HasField("angles") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("angles")
		x.Angles.MarshalProtoJSON(s.WithField("angles"))
	}
	if x.AspectRatio != 0 || s.HasField("aspectRatio") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("aspectRatio")
		s.WriteFloat64(x.AspectRatio)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the CameraKeyframe to JSON.
func (x *CameraKeyframe) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the CameraKeyframe message from JSON.
func (x *CameraKeyframe) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "time":
			s.AddField("time")
			x.Time = s.ReadFloat64()
		case "position":
			if s.ReadNil() {
				x.Position = nil
				return
			}
			x.Position = &Vec3{}
			x.Position.UnmarshalProtoJSON(s.WithField("position", true))
		case "angles":
			if s.ReadNil() {
				x.Angles = nil
				return
			}
			x.Angles = &EulerAngles{}
			x.Angles.UnmarshalProtoJSON(s.WithField("angles", true))
		case "aspect_ratio", "aspectRatio":
			s.AddField("aspect_ratio")
			x.AspectRatio = s.ReadFloat64()
		}
	})
}

// UnmarshalJSON unmarshals the CameraKeyframe from JSON.
func (x *CameraKeyframe) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the CameraPath message to JSON.
func (x *CameraPath) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Keys) > 0 || s.HasField("keys") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("keys")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Keys {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("keys"))
		}
		s.WriteArrayEnd()
	}
	if x.Interpolation != 0 || s.HasField("interpolation") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("interpolation")
		x.Interpolation.MarshalProtoJSON(s)
	}
	if x.RotationMode != 0 || s.HasField("rotationMode") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("rotationMode")
		x.RotationMode.MarshalProtoJSON(s)
	}
	if x.LensInterpolation != 0 || s.HasField("lensInterpolation") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("lensInterpolation")
		x.LensInterpolation.MarshalProtoJSON(s)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the CameraPath to JSON.
func (x *CameraPath) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the CameraPath message from JSON.
func (x *CameraPath) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "keys":
			s.AddField("keys")
			if s.ReadNil() {
				x.Keys = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Keys = append(x.Keys, nil)
					return
				}
				v := &CameraKeyframe{}
				v.UnmarshalProtoJSON(s.WithField("keys", false))
				if s.Err() != nil {
					return
				}
				x.Keys = append(x.Keys, v)
			})
		case "interpolation":
			s.AddField("interpolation")
			x.Interpolation.UnmarshalProtoJSON(s)
		case "rotation_mode", "rotationMode":
			s.AddField("rotation_mode")
			x.RotationMode.UnmarshalProtoJSON(s)
		case "lens_interpolation", "lensInterpolation":
			s.AddField("lens_interpolation")
			x.LensInterpolation.UnmarshalProtoJSON(s)
		}
	})
}

// UnmarshalJSON unmarshals the CameraPath from JSON.
func (x *CameraPath) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *CameraPose) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CameraPose) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CameraPose) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.AspectRatio != 0 {
		i = protobuf_go_lite.EncodeFixed64(dAtA, i, uint64(math.Float64bits(float64(m.AspectRatio))))
		i--
		dAtA[i] = 0x19
	}
	if m.Angles != nil {
		size, err := m.Angles.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Position != nil {
		size, err := m.Position.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CameraKeyframe) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CameraKeyframe) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CameraKeyframe) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.AspectRatio != 0 {
		i = protobuf_go_lite.EncodeFixed64(dAtA, i, uint64(math.Float64bits(float64(m.AspectRatio))))
		i--
		dAtA[i] = 0x21
	}
	if m.Angles != nil {
		size, err := m.Angles.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.Position != nil {
		size, err := m.Position.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Time != 0 {
		i = protobuf_go_lite.EncodeFixed64(dAtA, i, uint64(math.Float64bits(float64(m.Time))))
		i--
		dAtA[i] = 0x9
	}
	return len(dAtA) - i, nil
}

func (m *CameraPath) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CameraPath) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CameraPath) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.LensInterpolation != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.LensInterpolation))
		i--
		dAtA[i] = 0x20
	}
	if m.RotationMode != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.RotationMode))
		i--
		dAtA[i] = 0x18
	}
	if m.Interpolation != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Interpolation))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Keys) > 0 {
		for iNdEx := len(m.Keys) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Keys[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CameraPose) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Position != nil {
		l = m.Position.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.Angles != nil {
		l = m.Angles.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeFixed64NonZero(1, m.AspectRatio)
	n += len(m.unknownFields)
	return n
}

func (m *CameraKeyframe) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeFixed64NonZero(1, m.Time)
	if m.Position != nil {
		l = m.Position.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.Angles != nil {
		l = m.Angles.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeFixed64NonZero(1, m.AspectRatio)
	n += len(m.unknownFields)
	return n
}

func (m *CameraPath) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	for _, e := range m.Keys {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Interpolation)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.RotationMode)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.LensInterpolation)
	n += len(m.unknownFields)
	return n
}

func (x Interpolation) MarshalProtoText() string {
	return x.String()
}

func (x RotationMode) MarshalProtoText() string {
	return x.String()
}

func (x *CameraPose) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CameraPose")
	if x.Position != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "position")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Position)
	}
	if x.Angles != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "angles")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Angles)
	}
	if x.AspectRatio != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "aspect_ratio")
		protobuf_go_lite.TextWriteFloat64(&sb, x.AspectRatio)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CameraPose) String() string {
	return x.MarshalProtoText()
}

func (x *CameraKeyframe) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CameraKeyframe")
	if x.Time != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "time")
		protobuf_go_lite.TextWriteFloat64(&sb, x.Time)
	}
	if x.Position != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "position")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Position)
	}
	if x.Angles != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "angles")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Angles)
	}
	if x.AspectRatio != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "aspect_ratio")
		protobuf_go_lite.TextWriteFloat64(&sb, x.AspectRatio)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CameraKeyframe) String() string {
	return x.MarshalProtoText()
}

func (x *CameraPath) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CameraPath")
	if len(x.Keys) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "keys")
		for i, v := range x.Keys {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &CameraKeyframe{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if x.Interpolation != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "interpolation")
		protobuf_go_lite.TextWriteStringer(&sb, Interpolation(x.Interpolation))
	}
	if x.RotationMode != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "rotation_mode")
		protobuf_go_lite.TextWriteStringer(&sb, RotationMode(x.RotationMode))
	}
	if x.LensInterpolation != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "lens_interpolation")
		protobuf_go_lite.TextWriteStringer(&sb, Interpolation(x.LensInterpolation))
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CameraPath) String() string {
	return x.MarshalProtoText()
}

func (m *CameraPose) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CameraPose: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CameraPose: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Position == nil {
				m.Position = &Vec3{}
			}
			if err := m.Position.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Angles", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Angles == nil {
				m.Angles = &EulerAngles{}
			}
			if err := m.Angles.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field AspectRatio", wireType)
			}
			var v uint64
			var _v64 uint64
			_v64, iNdEx, err = protobuf_go_lite.DecodeFixed64(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint64(_v64)
			m.AspectRatio = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CameraKeyframe) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CameraKeyframe: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CameraKeyframe: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var v uint64
			var _v64 uint64
			_v64, iNdEx, err = protobuf_go_lite.DecodeFixed64(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint64(_v64)
			m.Time = float64(math.Float64frombits(v))
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Position == nil {
				m.Position = &Vec3{}
			}
			if err := m.Position.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Angles", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Angles == nil {
				m.Angles = &EulerAngles{}
			}
			if err := m.Angles.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field AspectRatio", wireType)
			}
			var v uint64
			var _v64 uint64
			_v64, iNdEx, err = protobuf_go_lite.DecodeFixed64(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint64(_v64)
			m.AspectRatio = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CameraPath) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CameraPath: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CameraPath: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keys", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Keys = append(m.Keys, &CameraKeyframe{})
			if err := m.Keys[len(m.Keys)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interpolation", wireType)
			}
			m.Interpolation = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.Interpolation = Interpolation(_v)
			if err != nil {
				return err
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RotationMode", wireType)
			}
			m.RotationMode = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.RotationMode = RotationMode(_v)
			if err != nil {
				return err
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LensInterpolation", wireType)
			}
			m.LensInterpolation = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.LensInterpolation = Interpolation(_v)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
