//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/paralin/modlock/proto/modlock/camera.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto_2epb_2eh
#define github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "types.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto MODLOCK_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct MODLOCK_API TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
MODLOCK_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto;
}  // extern "C"
namespace modlock {
enum Interpolation : int;
extern const uint32_t Interpolation_internal_data_[];
enum RotationMode : int;
extern const uint32_t RotationMode_internal_data_[];
class CameraKeyframe;
struct CameraKeyframeDefaultTypeInternal;
MODLOCK_API extern CameraKeyframeDefaultTypeInternal _CameraKeyframe_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull CameraKeyframe_class_data_;
class CameraPath;
struct CameraPathDefaultTypeInternal;
MODLOCK_API extern CameraPathDefaultTypeInternal _CameraPath_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull CameraPath_class_data_;
class CameraPose;
struct CameraPoseDefaultTypeInternal;
MODLOCK_API extern CameraPoseDefaultTypeInternal _CameraPose_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull CameraPose_class_data_;
}  // namespace modlock
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::modlock::Interpolation_internal_data_>
    internal::EnumTraitsImpl::value<::modlock::Interpolation>;
template <>
internal::EnumTraitsT<::modlock::RotationMode_internal_data_>
    internal::EnumTraitsImpl::value<::modlock::RotationMode>;
}  // namespace protobuf
}  // namespace google

namespace modlock {
enum Interpolation : int {
  INTERPOLATION_UNSPECIFIED = 0,
  INTERPOLATION_LINEAR = 1,
  INTERPOLATION_SMOOTH = 2,
  INTERPOLATION_STEP = 3,
  Interpolation_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Interpolation_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Interpolation_internal_data_[];
inline constexpr Interpolation Interpolation_MIN =
    static_cast<Interpolation>(0);
inline constexpr Interpolation Interpolation_MAX =
    static_cast<Interpolation>(3);
inline bool Interpolation_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int Interpolation_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Interpolation_descriptor();
template <typename T>
const ::std::string& Interpolation_Name(T value) {
  static_assert(::std::is_same<T, Interpolation>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Interpolation_Name().");
  return Interpolation_Name(static_cast<Interpolation>(value));
}
template <>
inline const ::std::string& Interpolation_Name(Interpolation value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Interpolation_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool Interpolation_Parse(
    ::absl::string_view name, Interpolation* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Interpolation>(Interpolation_descriptor(), name,
                                           value);
}
enum RotationMode : int {
  ROTATION_MODE_UNSPECIFIED = 0,
  ROTATION_MODE_SHORTEST = 1,
  ROTATION_MODE_UNWRAPPED = 2,
  RotationMode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RotationMode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RotationMode_internal_data_[];
inline constexpr RotationMode RotationMode_MIN =
    static_cast<RotationMode>(0);
inline constexpr RotationMode RotationMode_MAX =
    static_cast<RotationMode>(2);
inline bool RotationMode_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int RotationMode_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RotationMode_descriptor();
template <typename T>
const ::std::string& RotationMode_Name(T value) {
  static_assert(::std::is_same<T, RotationMode>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RotationMode_Name().");
  return RotationMode_Name(static_cast<RotationMode>(value));
}
template <>
inline const ::std::string& RotationMode_Name(RotationMode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RotationMode_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool RotationMode_Parse(
    ::absl::string_view name, RotationMode* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RotationMode>(RotationMode_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class MODLOCK_API CameraPose final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.CameraPose) */ {
 public:
  inline CameraPose() : CameraPose(nullptr) {}
  ~CameraPose() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CameraPose* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CameraPose));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CameraPose(::google::protobuf::internal::ConstantInitialized);

  inline CameraPose(const CameraPose& from) : CameraPose(nullptr, from) {}
  inline CameraPose(CameraPose&& from) noexcept
      : CameraPose(nullptr, ::std::move(from)) {}
  inline CameraPose& operator=(const CameraPose& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraPose& operator=(CameraPose&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CameraPose& default_instance() {
    return *reinterpret_cast<const CameraPose*>(
        &_CameraPose_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CameraPose& a, CameraPose& b) { a.Swap(&b); }
  inline void Swap(CameraPose* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraPose* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CameraPose* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CameraPose>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CameraPose& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CameraPose& from) { CameraPose::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CameraPose* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.CameraPose"; }

  explicit CameraPose(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CameraPose(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CameraPose& from);
  CameraPose(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CameraPose&& from) noexcept
      : CameraPose(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 1,
    kAnglesFieldNumber = 2,
    kAspectRatioFieldNumber = 3,
  };
  // .modlock.Vec3 position = 1;
  bool has_position() const;
  void clear_position() ;
  const ::modlock::Vec3& position() const;
  [[nodiscard]] ::modlock::Vec3* PROTOBUF_NULLABLE release_position();
  ::modlock::Vec3* PROTOBUF_NONNULL mutable_position();
  void set_allocated_position(::modlock::Vec3* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_position(::modlock::Vec3* PROTOBUF_NULLABLE value);
  ::modlock::Vec3* PROTOBUF_NULLABLE unsafe_arena_release_position();

  private:
  const ::modlock::Vec3& _internal_position() const;
  ::modlock::Vec3* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // .modlock.EulerAngles angles = 2;
  bool has_angles() const;
  void clear_angles() ;
  const ::modlock::EulerAngles& angles() const;
  [[nodiscard]] ::modlock::EulerAngles* PROTOBUF_NULLABLE release_angles();
  ::modlock::EulerAngles* PROTOBUF_NONNULL mutable_angles();
  void set_allocated_angles(::modlock::EulerAngles* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_angles(::modlock::EulerAngles* PROTOBUF_NULLABLE value);
  ::modlock::EulerAngles* PROTOBUF_NULLABLE unsafe_arena_release_angles();

  private:
  const ::modlock::EulerAngles& _internal_angles() const;
  ::modlock::EulerAngles* PROTOBUF_NONNULL _internal_mutable_angles();

  public:
  // double aspect_ratio = 3;
  void clear_aspect_ratio() ;
  double aspect_ratio() const;
  void set_aspect_ratio(double value);

  private:
  double _internal_aspect_ratio() const;
  void _internal_set_aspect_ratio(double value);

  public:
  // @@protoc_insertion_point(class_scope:modlock.CameraPose)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CameraPose& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::modlock::Vec3* PROTOBUF_NULLABLE position_;
    ::modlock::EulerAngles* PROTOBUF_NULLABLE angles_;
    double aspect_ratio_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull CameraPose_class_data_;
// -------------------------------------------------------------------

class MODLOCK_API CameraKeyframe final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.CameraKeyframe) */ {
 public:
  inline CameraKeyframe() : CameraKeyframe(nullptr) {}
  ~CameraKeyframe() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CameraKeyframe* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CameraKeyframe));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CameraKeyframe(::google::protobuf::internal::ConstantInitialized);

  inline CameraKeyframe(const CameraKeyframe& from) : CameraKeyframe(nullptr, from) {}
  inline CameraKeyframe(CameraKeyframe&& from) noexcept
      : CameraKeyframe(nullptr, ::std::move(from)) {}
  inline CameraKeyframe& operator=(const CameraKeyframe& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraKeyframe& operator=(CameraKeyframe&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CameraKeyframe& default_instance() {
    return *reinterpret_cast<const CameraKeyframe*>(
        &_CameraKeyframe_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CameraKeyframe& a, CameraKeyframe& b) { a.Swap(&b); }
  inline void Swap(CameraKeyframe* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraKeyframe* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CameraKeyframe* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CameraKeyframe>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CameraKeyframe& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CameraKeyframe& from) { CameraKeyframe::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CameraKeyframe* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.CameraKeyframe"; }

  explicit CameraKeyframe(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CameraKeyframe(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CameraKeyframe& from);
  CameraKeyframe(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CameraKeyframe&& from) noexcept
      : CameraKeyframe(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 2,
    kAnglesFieldNumber = 3,
    kTimeFieldNumber = 1,
    kAspectRatioFieldNumber = 4,
  };
  // .modlock.Vec3 position = 2;
  bool has_position() const;
  void clear_position() ;
  const ::modlock::Vec3& position() const;
  [[nodiscard]] ::modlock::Vec3* PROTOBUF_NULLABLE release_position();
  ::modlock::Vec3* PROTOBUF_NONNULL mutable_position();
  void set_allocated_position(::modlock::Vec3* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_position(::modlock::Vec3* PROTOBUF_NULLABLE value);
  ::modlock::Vec3* PROTOBUF_NULLABLE unsafe_arena_release_position();

  private:
  const ::modlock::Vec3& _internal_position() const;
  ::modlock::Vec3* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // .modlock.EulerAngles angles = 3;
  bool has_angles() const;
  void clear_angles() ;
  const ::modlock::EulerAngles& angles() const;
  [[nodiscard]] ::modlock::EulerAngles* PROTOBUF_NULLABLE release_angles();
  ::modlock::EulerAngles* PROTOBUF_NONNULL mutable_angles();
  void set_allocated_angles(::modlock::EulerAngles* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_angles(::modlock::EulerAngles* PROTOBUF_NULLABLE value);
  ::modlock::EulerAngles* PROTOBUF_NULLABLE unsafe_arena_release_angles();

  private:
  const ::modlock::EulerAngles& _internal_angles() const;
  ::modlock::EulerAngles* PROTOBUF_NONNULL _internal_mutable_angles();

  public:
  // double time = 1;
  void clear_time() ;
  double time() const;
  void set_time(double value);

  private:
  double _internal_time() const;
  void _internal_set_time(double value);

  public:
  // double aspect_ratio = 4;
  void clear_aspect_ratio() ;
  double aspect_ratio() const;
  void set_aspect_ratio(double value);

  private:
  double _internal_aspect_ratio() const;
  void _internal_set_aspect_ratio(double value);

  public:
  // @@protoc_insertion_point(class_scope:modlock.CameraKeyframe)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CameraKeyframe& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::modlock::Vec3* PROTOBUF_NULLABLE position_;
    ::modlock::EulerAngles* PROTOBUF_NULLABLE angles_;
    double time_;
    double aspect_ratio_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull CameraKeyframe_class_data_;
// -------------------------------------------------------------------

class MODLOCK_API CameraPath final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.CameraPath) */ {
 public:
  inline CameraPath() : CameraPath(nullptr) {}
  ~CameraPath() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CameraPath* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CameraPath));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CameraPath(::google::protobuf::internal::ConstantInitialized);

  inline CameraPath(const CameraPath& from) : CameraPath(nullptr, from) {}
  inline CameraPath(CameraPath&& from) noexcept
      : CameraPath(nullptr, ::std::move(from)) {}
  inline CameraPath& operator=(const CameraPath& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraPath& operator=(CameraPath&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CameraPath& default_instance() {
    return *reinterpret_cast<const CameraPath*>(
        &_CameraPath_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CameraPath& a, CameraPath& b) { a.Swap(&b); }
  inline void Swap(CameraPath* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraPath* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CameraPath* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CameraPath>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CameraPath& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CameraPath& from) { CameraPath::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CameraPath* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.CameraPath"; }

  explicit CameraPath(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CameraPath(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CameraPath& from);
  CameraPath(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CameraPath&& from) noexcept
      : CameraPath(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kKeysFieldNumber = 1,
    kInterpolationFieldNumber = 2,
    kRotationModeFieldNumber = 3,
    kLensInterpolationFieldNumber = 4,
  };
  // repeated .modlock.CameraKeyframe keys = 1;
  int keys_size() const;
  private:
  int _internal_keys_size() const;

  public:
  void clear_keys() ;
  ::modlock::CameraKeyframe* PROTOBUF_NONNULL mutable_keys(int index);
  ::google::protobuf::RepeatedPtrField<::modlock::CameraKeyframe>* PROTOBUF_NONNULL mutable_keys();

  private:
  const ::google::protobuf::RepeatedPtrField<::modlock::CameraKeyframe>& _internal_keys() const;
  ::google::protobuf::RepeatedPtrField<::modlock::CameraKeyframe>* PROTOBUF_NONNULL _internal_mutable_keys();
  public:
  const ::modlock::CameraKeyframe& keys(int index) const;
  ::modlock::CameraKeyframe* PROTOBUF_NONNULL add_keys();
  const ::google::protobuf::RepeatedPtrField<::modlock::CameraKeyframe>& keys() const;
  // .modlock.Interpolation interpolation = 2;
  void clear_interpolation() ;
  ::modlock::Interpolation interpolation() const;
  void set_interpolation(::modlock::Interpolation value);

  private:
  ::modlock::Interpolation _internal_interpolation() const;
  void _internal_set_interpolation(::modlock::Interpolation value);

  public:
  // .modlock.RotationMode rotation_mode = 3;
  void clear_rotation_mode() ;
  ::modlock::RotationMode rotation_mode() const;
  void set_rotation_mode(::modlock::RotationMode value);

  private:
  ::modlock::RotationMode _internal_rotation_mode() const;
  void _internal_set_rotation_mode(::modlock::RotationMode value);

  public:
  // .modlock.Interpolation lens_interpolation = 4;
  void clear_lens_interpolation() ;
  ::modlock::Interpolation lens_interpolation() const;
  void set_lens_interpolation(::modlock::Interpolation value);

  private:
  ::modlock::Interpolation _internal_lens_interpolation() const;
  void _internal_set_lens_interpolation(::modlock::Interpolation value);

  public:
  // @@protoc_insertion_point(class_scope:modlock.CameraPath)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CameraPath& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::modlock::CameraKeyframe > keys_;
    int interpolation_;
    int rotation_mode_;
    int lens_interpolation_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull CameraPath_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CameraPose

// .modlock.Vec3 position = 1;
inline bool CameraPose::has_position() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline const ::modlock::Vec3& CameraPose::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::modlock::Vec3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::modlock::Vec3&>(::modlock::_Vec3_default_instance_);
}
inline const ::modlock::Vec3& CameraPose::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.CameraPose.position)
  return _internal_position();
}
inline void CameraPose::unsafe_arena_set_allocated_position(
    ::modlock::Vec3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::modlock::Vec3*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:modlock.CameraPose.position)
}
inline ::modlock::Vec3* PROTOBUF_NULLABLE CameraPose::release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::modlock::Vec3* released = _impl_.position_;
  _impl_.position_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::modlock::Vec3* PROTOBUF_NULLABLE CameraPose::unsafe_arena_release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.CameraPose.position)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::modlock::Vec3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::modlock::Vec3* PROTOBUF_NONNULL CameraPose::_internal_mutable_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::modlock::Vec3>(GetArena());
    _impl_.position_ = reinterpret_cast<::modlock::Vec3*>(p);
  }
  return _impl_.position_;
}
inline ::modlock::Vec3* PROTOBUF_NONNULL CameraPose::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::modlock::Vec3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:modlock.CameraPose.position)
  return _msg;
}
inline void CameraPose::set_allocated_position(::modlock::Vec3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.position_ = reinterpret_cast<::modlock::Vec3*>(value);
  // @@protoc_insertion_point(field_set_allocated:modlock.CameraPose.position)
}

// .modlock.EulerAngles angles = 2;
inline bool CameraPose::has_angles() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.angles_ != nullptr);
  return value;
}
inline const ::modlock::EulerAngles& CameraPose::_internal_angles() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::modlock::EulerAngles* p = _impl_.angles_;
  return p != nullptr ? *p : reinterpret_cast<const ::modlock::EulerAngles&>(::modlock::_EulerAngles_default_instance_);
}
inline const ::modlock::EulerAngles& CameraPose::angles() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.CameraPose.angles)
  return _internal_angles();
}
inline void CameraPose::unsafe_arena_set_allocated_angles(
    ::modlock::EulerAngles* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.angles_);
  }
  _impl_.angles_ = reinterpret_cast<::modlock::EulerAngles*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:modlock.CameraPose.angles)
}
inline ::modlock::EulerAngles* PROTOBUF_NULLABLE CameraPose::release_angles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::modlock::EulerAngles* released = _impl_.angles_;
  _impl_.angles_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::modlock::EulerAngles* PROTOBUF_NULLABLE CameraPose::unsafe_arena_release_angles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.CameraPose.angles)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::modlock::EulerAngles* temp = _impl_.angles_;
  _impl_.angles_ = nullptr;
  return temp;
}
inline ::modlock::EulerAngles* PROTOBUF_NONNULL CameraPose::_internal_mutable_angles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.angles_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::modlock::EulerAngles>(GetArena());
    _impl_.angles_ = reinterpret_cast<::modlock::EulerAngles*>(p);
  }
  return _impl_.angles_;
}
inline ::modlock::EulerAngles* PROTOBUF_NONNULL CameraPose::mutable_angles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::modlock::EulerAngles* _msg = _internal_mutable_angles();
  // @@protoc_insertion_point(field_mutable:modlock.CameraPose.angles)
  return _msg;
}
inline void CameraPose::set_allocated_angles(::modlock::EulerAngles* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.angles_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.angles_ = reinterpret_cast<::modlock::EulerAngles*>(value);
  // @@protoc_insertion_point(field_set_allocated:modlock.CameraPose.angles)
}

// double aspect_ratio = 3;
inline void CameraPose::clear_aspect_ratio() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aspect_ratio_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double CameraPose::aspect_ratio() const {
  // @@protoc_insertion_point(field_get:modlock.CameraPose.aspect_ratio)
  return _internal_aspect_ratio();
}
inline void CameraPose::set_aspect_ratio(double value) {
  _internal_set_aspect_ratio(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:modlock.CameraPose.aspect_ratio)
}
inline double CameraPose::_internal_aspect_ratio() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.aspect_ratio_;
}
inline void CameraPose::_internal_set_aspect_ratio(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aspect_ratio_ = value;
}

// -------------------------------------------------------------------

// CameraKeyframe

// double time = 1;
inline void CameraKeyframe::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double CameraKeyframe::time() const {
  // @@protoc_insertion_point(field_get:modlock.CameraKeyframe.time)
  return _internal_time();
}
inline void CameraKeyframe::set_time(double value) {
  _internal_set_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:modlock.CameraKeyframe.time)
}
inline double CameraKeyframe::_internal_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_;
}
inline void CameraKeyframe::_internal_set_time(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = value;
}

// .modlock.Vec3 position = 2;
inline bool CameraKeyframe::has_position() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline const ::modlock::Vec3& CameraKeyframe::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::modlock::Vec3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::modlock::Vec3&>(::modlock::_Vec3_default_instance_);
}
inline const ::modlock::Vec3& CameraKeyframe::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.CameraKeyframe.position)
  return _internal_position();
}
inline void CameraKeyframe::unsafe_arena_set_allocated_position(
    ::modlock::Vec3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::modlock::Vec3*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:modlock.CameraKeyframe.position)
}
inline ::modlock::Vec3* PROTOBUF_NULLABLE CameraKeyframe::release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::modlock::Vec3* released = _impl_.position_;
  _impl_.position_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::modlock::Vec3* PROTOBUF_NULLABLE CameraKeyframe::unsafe_arena_release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.CameraKeyframe.position)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::modlock::Vec3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::modlock::Vec3* PROTOBUF_NONNULL CameraKeyframe::_internal_mutable_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::modlock::Vec3>(GetArena());
    _impl_.position_ = reinterpret_cast<::modlock::Vec3*>(p);
  }
  return _impl_.position_;
}
inline ::modlock::Vec3* PROTOBUF_NONNULL CameraKeyframe::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::modlock::Vec3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:modlock.CameraKeyframe.position)
  return _msg;
}
inline void CameraKeyframe::set_allocated_position(::modlock::Vec3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.position_ = reinterpret_cast<::modlock::Vec3*>(value);
  // @@protoc_insertion_point(field_set_allocated:modlock.CameraKeyframe.position)
}

// .modlock.EulerAngles angles = 3;
inline bool CameraKeyframe::has_angles() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.angles_ != nullptr);
  return value;
}
inline const ::modlock::EulerAngles& CameraKeyframe::_internal_angles() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::modlock::EulerAngles* p = _impl_.angles_;
  return p != nullptr ? *p : reinterpret_cast<const ::modlock::EulerAngles&>(::modlock::_EulerAngles_default_instance_);
}
inline const ::modlock::EulerAngles& CameraKeyframe::angles() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.CameraKeyframe.angles)
  return _internal_angles();
}
inline void CameraKeyframe::unsafe_arena_set_allocated_angles(
    ::modlock::EulerAngles* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.angles_);
  }
  _impl_.angles_ = reinterpret_cast<::modlock::EulerAngles*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:modlock.CameraKeyframe.angles)
}
inline ::modlock::EulerAngles* PROTOBUF_NULLABLE CameraKeyframe::release_angles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::modlock::EulerAngles* released = _impl_.angles_;
  _impl_.angles_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::modlock::EulerAngles* PROTOBUF_NULLABLE CameraKeyframe::unsafe_arena_release_angles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.CameraKeyframe.angles)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::modlock::EulerAngles* temp = _impl_.angles_;
  _impl_.angles_ = nullptr;
  return temp;
}
inline ::modlock::EulerAngles* PROTOBUF_NONNULL CameraKeyframe::_internal_mutable_angles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.angles_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::modlock::EulerAngles>(GetArena());
    _impl_.angles_ = reinterpret_cast<::modlock::EulerAngles*>(p);
  }
  return _impl_.angles_;
}
inline ::modlock::EulerAngles* PROTOBUF_NONNULL CameraKeyframe::mutable_angles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::modlock::EulerAngles* _msg = _internal_mutable_angles();
  // @@protoc_insertion_point(field_mutable:modlock.CameraKeyframe.angles)
  return _msg;
}
inline void CameraKeyframe::set_allocated_angles(::modlock::EulerAngles* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.angles_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.angles_ = reinterpret_cast<::modlock::EulerAngles*>(value);
  // @@protoc_insertion_point(field_set_allocated:modlock.CameraKeyframe.angles)
}

// double aspect_ratio = 4;
inline void CameraKeyframe::clear_aspect_ratio() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aspect_ratio_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double CameraKeyframe::aspect_ratio() const {
  // @@protoc_insertion_point(field_get:modlock.CameraKeyframe.aspect_ratio)
  return _internal_aspect_ratio();
}
inline void CameraKeyframe::set_aspect_ratio(double value) {
  _internal_set_aspect_ratio(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:modlock.CameraKeyframe.aspect_ratio)
}
inline double CameraKeyframe::_internal_aspect_ratio() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.aspect_ratio_;
}
inline void CameraKeyframe::_internal_set_aspect_ratio(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aspect_ratio_ = value;
}

// -------------------------------------------------------------------

// CameraPath

// repeated .modlock.CameraKeyframe keys = 1;
inline int CameraPath::_internal_keys_size() const {
  return _internal_keys().size();
}
inline int CameraPath::keys_size() const {
  return _internal_keys_size();
}
inline void CameraPath::clear_keys() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keys_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::modlock::CameraKeyframe* PROTOBUF_NONNULL CameraPath::mutable_keys(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:modlock.CameraPath.keys)
  return _internal_mutable_keys()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::modlock::CameraKeyframe>* PROTOBUF_NONNULL CameraPath::mutable_keys()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:modlock.CameraPath.keys)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_keys();
}
inline const ::modlock::CameraKeyframe& CameraPath::keys(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.CameraPath.keys)
  return _internal_keys().Get(index);
}
inline ::modlock::CameraKeyframe* PROTOBUF_NONNULL CameraPath::add_keys()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::modlock::CameraKeyframe* _add =
      _internal_mutable_keys()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:modlock.CameraPath.keys)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::modlock::CameraKeyframe>& CameraPath::keys() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:modlock.CameraPath.keys)
  return _internal_keys();
}
inline const ::google::protobuf::RepeatedPtrField<::modlock::CameraKeyframe>&
CameraPath::_internal_keys() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.keys_;
}
inline ::google::protobuf::RepeatedPtrField<::modlock::CameraKeyframe>* PROTOBUF_NONNULL
CameraPath::_internal_mutable_keys() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.keys_;
}

// .modlock.Interpolation interpolation = 2;
inline void CameraPath::clear_interpolation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.interpolation_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::modlock::Interpolation CameraPath::interpolation() const {
  // @@protoc_insertion_point(field_get:modlock.CameraPath.interpolation)
  return _internal_interpolation();
}
inline void CameraPath::set_interpolation(::modlock::Interpolation value) {
  _internal_set_interpolation(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:modlock.CameraPath.interpolation)
}
inline ::modlock::Interpolation CameraPath::_internal_interpolation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::modlock::Interpolation>(_impl_.interpolation_);
}
inline void CameraPath::_internal_set_interpolation(::modlock::Interpolation value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.interpolation_ = value;
}

// .modlock.RotationMode rotation_mode = 3;
inline void CameraPath::clear_rotation_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rotation_mode_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::modlock::RotationMode CameraPath::rotation_mode() const {
  // @@protoc_insertion_point(field_get:modlock.CameraPath.rotation_mode)
  return _internal_rotation_mode();
}
inline void CameraPath::set_rotation_mode(::modlock::RotationMode value) {
  _internal_set_rotation_mode(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:modlock.CameraPath.rotation_mode)
}
inline ::modlock::RotationMode CameraPath::_internal_rotation_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::modlock::RotationMode>(_impl_.rotation_mode_);
}
inline void CameraPath::_internal_set_rotation_mode(::modlock::RotationMode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rotation_mode_ = value;
}

// .modlock.Interpolation lens_interpolation = 4;
inline void CameraPath::clear_lens_interpolation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lens_interpolation_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::modlock::Interpolation CameraPath::lens_interpolation() const {
  // @@protoc_insertion_point(field_get:modlock.CameraPath.lens_interpolation)
  return _internal_lens_interpolation();
}
inline void CameraPath::set_lens_interpolation(::modlock::Interpolation value) {
  _internal_set_lens_interpolation(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:modlock.CameraPath.lens_interpolation)
}
inline ::modlock::Interpolation CameraPath::_internal_lens_interpolation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::modlock::Interpolation>(_impl_.lens_interpolation_);
}
inline void CameraPath::_internal_set_lens_interpolation(::modlock::Interpolation value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lens_interpolation_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace modlock


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::modlock::Interpolation> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::modlock::Interpolation>() {
  return ::modlock::Interpolation_descriptor();
}
template <>
struct is_proto_enum<::modlock::RotationMode> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::modlock::RotationMode>() {
  return ::modlock::RotationMode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fcamera_2eproto_2epb_2eh
