//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/paralin/modlock/proto/modlock/chat.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fchat_2eproto_2epb_2eh
#define github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fchat_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fchat_2eproto MODLOCK_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct MODLOCK_API TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fchat_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
MODLOCK_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fchat_2eproto;
}  // extern "C"
namespace modlock {
namespace engine {
class ChatMessage;
struct ChatMessageDefaultTypeInternal;
MODLOCK_API extern ChatMessageDefaultTypeInternal _ChatMessage_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull ChatMessage_class_data_;
class PlayerChatMessage;
struct PlayerChatMessageDefaultTypeInternal;
MODLOCK_API extern PlayerChatMessageDefaultTypeInternal _PlayerChatMessage_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull PlayerChatMessage_class_data_;
}  // namespace engine
}  // namespace modlock
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace modlock {
namespace engine {

// ===================================================================


// -------------------------------------------------------------------

class MODLOCK_API PlayerChatMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.engine.PlayerChatMessage) */ {
 public:
  inline PlayerChatMessage() : PlayerChatMessage(nullptr) {}
  ~PlayerChatMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlayerChatMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlayerChatMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlayerChatMessage(::google::protobuf::internal::ConstantInitialized);

  inline PlayerChatMessage(const PlayerChatMessage& from) : PlayerChatMessage(nullptr, from) {}
  inline PlayerChatMessage(PlayerChatMessage&& from) noexcept
      : PlayerChatMessage(nullptr, ::std::move(from)) {}
  inline PlayerChatMessage& operator=(const PlayerChatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerChatMessage& operator=(PlayerChatMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerChatMessage& default_instance() {
    return *reinterpret_cast<const PlayerChatMessage*>(
        &_PlayerChatMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PlayerChatMessage& a, PlayerChatMessage& b) { a.Swap(&b); }
  inline void Swap(PlayerChatMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerChatMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerChatMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlayerChatMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlayerChatMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlayerChatMessage& from) { PlayerChatMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlayerChatMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.engine.PlayerChatMessage"; }

  explicit PlayerChatMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlayerChatMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlayerChatMessage& from);
  PlayerChatMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlayerChatMessage&& from) noexcept
      : PlayerChatMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageNameFieldNumber = 3,
    kPlayerNameFieldNumber = 4,
    kTextFieldNumber = 5,
    kParam3FieldNumber = 6,
    kParam4FieldNumber = 7,
    kChatFieldNumber = 2,
    kEntityIndexFieldNumber = 1,
  };
  // optional string message_name = 3;
  bool has_message_name() const;
  void clear_message_name() ;
  const ::std::string& message_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message_name();
  void set_allocated_message_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_message_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message_name();

  public:
  // optional string player_name = 4;
  bool has_player_name() const;
  void clear_player_name() ;
  const ::std::string& player_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_player_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_player_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_player_name();
  void set_allocated_player_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_player_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_player_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_player_name();

  public:
  // optional string text = 5;
  bool has_text() const;
  void clear_text() ;
  const ::std::string& text() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_text();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_text();
  void set_allocated_text(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_text() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_text(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_text();

  public:
  // optional string param3 = 6;
  bool has_param3() const;
  void clear_param3() ;
  const ::std::string& param3() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_param3(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_param3();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_param3();
  void set_allocated_param3(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_param3() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_param3(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_param3();

  public:
  // optional string param4 = 7;
  bool has_param4() const;
  void clear_param4() ;
  const ::std::string& param4() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_param4(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_param4();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_param4();
  void set_allocated_param4(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_param4() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_param4(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_param4();

  public:
  // optional bool chat = 2;
  bool has_chat() const;
  void clear_chat() ;
  bool chat() const;
  void set_chat(bool value);

  private:
  bool _internal_chat() const;
  void _internal_set_chat(bool value);

  public:
  // optional int32 entity_index = 1 [default = -1];
  bool has_entity_index() const;
  void clear_entity_index() ;
  ::int32_t entity_index() const;
  void set_entity_index(::int32_t value);

  private:
  ::int32_t _internal_entity_index() const;
  void _internal_set_entity_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:modlock.engine.PlayerChatMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlayerChatMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr message_name_;
    ::google::protobuf::internal::ArenaStringPtr player_name_;
    ::google::protobuf::internal::ArenaStringPtr text_;
    ::google::protobuf::internal::ArenaStringPtr param3_;
    ::google::protobuf::internal::ArenaStringPtr param4_;
    bool chat_;
    ::int32_t entity_index_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fchat_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull PlayerChatMessage_class_data_;
// -------------------------------------------------------------------

class MODLOCK_API ChatMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.engine.ChatMessage) */ {
 public:
  inline ChatMessage() : ChatMessage(nullptr) {}
  ~ChatMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ChatMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ChatMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ChatMessage(::google::protobuf::internal::ConstantInitialized);

  inline ChatMessage(const ChatMessage& from) : ChatMessage(nullptr, from) {}
  inline ChatMessage(ChatMessage&& from) noexcept
      : ChatMessage(nullptr, ::std::move(from)) {}
  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatMessage& operator=(ChatMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatMessage& default_instance() {
    return *reinterpret_cast<const ChatMessage*>(
        &_ChatMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ChatMessage& a, ChatMessage& b) { a.Swap(&b); }
  inline void Swap(ChatMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ChatMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ChatMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ChatMessage& from) { ChatMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ChatMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.engine.ChatMessage"; }

  explicit ChatMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ChatMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ChatMessage& from);
  ChatMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ChatMessage&& from) noexcept
      : ChatMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTextFieldNumber = 2,
    kAllChatFieldNumber = 3,
    kPlayerSlotFieldNumber = 1,
  };
  // optional string text = 2;
  bool has_text() const;
  void clear_text() ;
  const ::std::string& text() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_text();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_text();
  void set_allocated_text(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_text() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_text(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_text();

  public:
  // optional bool all_chat = 3;
  bool has_all_chat() const;
  void clear_all_chat() ;
  bool all_chat() const;
  void set_all_chat(bool value);

  private:
  bool _internal_all_chat() const;
  void _internal_set_all_chat(bool value);

  public:
  // optional int32 player_slot = 1 [default = -1];
  bool has_player_slot() const;
  void clear_player_slot() ;
  ::int32_t player_slot() const;
  void set_player_slot(::int32_t value);

  private:
  ::int32_t _internal_player_slot() const;
  void _internal_set_player_slot(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:modlock.engine.ChatMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ChatMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr text_;
    bool all_chat_;
    ::int32_t player_slot_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fchat_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull ChatMessage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PlayerChatMessage

// optional int32 entity_index = 1 [default = -1];
inline bool PlayerChatMessage::has_entity_index() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void PlayerChatMessage::clear_entity_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entity_index_ = -1;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t PlayerChatMessage::entity_index() const {
  // @@protoc_insertion_point(field_get:modlock.engine.PlayerChatMessage.entity_index)
  return _internal_entity_index();
}
inline void PlayerChatMessage::set_entity_index(::int32_t value) {
  _internal_set_entity_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:modlock.engine.PlayerChatMessage.entity_index)
}
inline ::int32_t PlayerChatMessage::_internal_entity_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entity_index_;
}
inline void PlayerChatMessage::_internal_set_entity_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entity_index_ = value;
}

// optional bool chat = 2;
inline bool PlayerChatMessage::has_chat() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void PlayerChatMessage::clear_chat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chat_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline bool PlayerChatMessage::chat() const {
  // @@protoc_insertion_point(field_get:modlock.engine.PlayerChatMessage.chat)
  return _internal_chat();
}
inline void PlayerChatMessage::set_chat(bool value) {
  _internal_set_chat(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:modlock.engine.PlayerChatMessage.chat)
}
inline bool PlayerChatMessage::_internal_chat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chat_;
}
inline void PlayerChatMessage::_internal_set_chat(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chat_ = value;
}

// optional string message_name = 3;
inline bool PlayerChatMessage::has_message_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PlayerChatMessage::clear_message_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& PlayerChatMessage::message_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.PlayerChatMessage.message_name)
  return _internal_message_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PlayerChatMessage::set_message_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.message_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.engine.PlayerChatMessage.message_name)
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::mutable_message_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_message_name();
  // @@protoc_insertion_point(field_mutable:modlock.engine.PlayerChatMessage.message_name)
  return _s;
}
inline const ::std::string& PlayerChatMessage::_internal_message_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_name_.Get();
}
inline void PlayerChatMessage::_internal_set_message_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::_internal_mutable_message_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PlayerChatMessage::release_message_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.engine.PlayerChatMessage.message_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.message_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_name_.Set("", GetArena());
  }
  return released;
}
inline void PlayerChatMessage::set_allocated_message_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.message_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_name_.IsDefault()) {
    _impl_.message_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.engine.PlayerChatMessage.message_name)
}

// optional string player_name = 4;
inline bool PlayerChatMessage::has_player_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void PlayerChatMessage::clear_player_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& PlayerChatMessage::player_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.PlayerChatMessage.player_name)
  return _internal_player_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PlayerChatMessage::set_player_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.player_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.engine.PlayerChatMessage.player_name)
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::mutable_player_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_player_name();
  // @@protoc_insertion_point(field_mutable:modlock.engine.PlayerChatMessage.player_name)
  return _s;
}
inline const ::std::string& PlayerChatMessage::_internal_player_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_name_.Get();
}
inline void PlayerChatMessage::_internal_set_player_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::_internal_mutable_player_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.player_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PlayerChatMessage::release_player_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.engine.PlayerChatMessage.player_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.player_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.player_name_.Set("", GetArena());
  }
  return released;
}
inline void PlayerChatMessage::set_allocated_player_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.player_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.player_name_.IsDefault()) {
    _impl_.player_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.engine.PlayerChatMessage.player_name)
}

// optional string text = 5;
inline bool PlayerChatMessage::has_text() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void PlayerChatMessage::clear_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& PlayerChatMessage::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.PlayerChatMessage.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PlayerChatMessage::set_text(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.engine.PlayerChatMessage.text)
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::mutable_text()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:modlock.engine.PlayerChatMessage.text)
  return _s;
}
inline const ::std::string& PlayerChatMessage::_internal_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.text_.Get();
}
inline void PlayerChatMessage::_internal_set_text(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::_internal_mutable_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.text_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PlayerChatMessage::release_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.engine.PlayerChatMessage.text)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.text_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.text_.Set("", GetArena());
  }
  return released;
}
inline void PlayerChatMessage::set_allocated_text(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.engine.PlayerChatMessage.text)
}

// optional string param3 = 6;
inline bool PlayerChatMessage::has_param3() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void PlayerChatMessage::clear_param3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.param3_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& PlayerChatMessage::param3() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.PlayerChatMessage.param3)
  return _internal_param3();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PlayerChatMessage::set_param3(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.param3_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.engine.PlayerChatMessage.param3)
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::mutable_param3()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_param3();
  // @@protoc_insertion_point(field_mutable:modlock.engine.PlayerChatMessage.param3)
  return _s;
}
inline const ::std::string& PlayerChatMessage::_internal_param3() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.param3_.Get();
}
inline void PlayerChatMessage::_internal_set_param3(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.param3_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::_internal_mutable_param3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.param3_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PlayerChatMessage::release_param3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.engine.PlayerChatMessage.param3)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.param3_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.param3_.Set("", GetArena());
  }
  return released;
}
inline void PlayerChatMessage::set_allocated_param3(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.param3_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.param3_.IsDefault()) {
    _impl_.param3_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.engine.PlayerChatMessage.param3)
}

// optional string param4 = 7;
inline bool PlayerChatMessage::has_param4() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void PlayerChatMessage::clear_param4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.param4_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& PlayerChatMessage::param4() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.PlayerChatMessage.param4)
  return _internal_param4();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PlayerChatMessage::set_param4(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.param4_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.engine.PlayerChatMessage.param4)
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::mutable_param4()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_param4();
  // @@protoc_insertion_point(field_mutable:modlock.engine.PlayerChatMessage.param4)
  return _s;
}
inline const ::std::string& PlayerChatMessage::_internal_param4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.param4_.Get();
}
inline void PlayerChatMessage::_internal_set_param4(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.param4_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PlayerChatMessage::_internal_mutable_param4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.param4_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PlayerChatMessage::release_param4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.engine.PlayerChatMessage.param4)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.param4_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.param4_.Set("", GetArena());
  }
  return released;
}
inline void PlayerChatMessage::set_allocated_param4(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.param4_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.param4_.IsDefault()) {
    _impl_.param4_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.engine.PlayerChatMessage.param4)
}

// -------------------------------------------------------------------

// ChatMessage

// optional int32 player_slot = 1 [default = -1];
inline bool ChatMessage::has_player_slot() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void ChatMessage::clear_player_slot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_slot_ = -1;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t ChatMessage::player_slot() const {
  // @@protoc_insertion_point(field_get:modlock.engine.ChatMessage.player_slot)
  return _internal_player_slot();
}
inline void ChatMessage::set_player_slot(::int32_t value) {
  _internal_set_player_slot(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:modlock.engine.ChatMessage.player_slot)
}
inline ::int32_t ChatMessage::_internal_player_slot() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_slot_;
}
inline void ChatMessage::_internal_set_player_slot(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_slot_ = value;
}

// optional string text = 2;
inline bool ChatMessage::has_text() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void ChatMessage::clear_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ChatMessage::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.ChatMessage.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ChatMessage::set_text(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.engine.ChatMessage.text)
}
inline ::std::string* PROTOBUF_NONNULL ChatMessage::mutable_text()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:modlock.engine.ChatMessage.text)
  return _s;
}
inline const ::std::string& ChatMessage::_internal_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.text_.Get();
}
inline void ChatMessage::_internal_set_text(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ChatMessage::_internal_mutable_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.text_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ChatMessage::release_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.engine.ChatMessage.text)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.text_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.text_.Set("", GetArena());
  }
  return released;
}
inline void ChatMessage::set_allocated_text(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.engine.ChatMessage.text)
}

// optional bool all_chat = 3;
inline bool ChatMessage::has_all_chat() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void ChatMessage::clear_all_chat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.all_chat_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool ChatMessage::all_chat() const {
  // @@protoc_insertion_point(field_get:modlock.engine.ChatMessage.all_chat)
  return _internal_all_chat();
}
inline void ChatMessage::set_all_chat(bool value) {
  _internal_set_all_chat(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:modlock.engine.ChatMessage.all_chat)
}
inline bool ChatMessage::_internal_all_chat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.all_chat_;
}
inline void ChatMessage::_internal_set_all_chat(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.all_chat_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace engine
}  // namespace modlock


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fchat_2eproto_2epb_2eh
