//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/paralin/modlock/proto/modlock/hud.proto
// Protobuf C++ Version: 6.33.4

#include "hud.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace modlock {
namespace engine {

inline constexpr HudTextMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        param_{},
        dest_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR HudTextMessage::HudTextMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HudTextMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HudTextMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HudTextMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HudTextMessageDefaultTypeInternal() {}
  union {
    HudTextMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT MODLOCK_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HudTextMessageDefaultTypeInternal _HudTextMessage_default_instance_;

inline constexpr HudAnnouncement::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        classname_{},
        dialog_variable_name_{},
        dialog_variable_locstring_{},
        title_locstring_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        description_locstring_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR HudAnnouncement::HudAnnouncement(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HudAnnouncement_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HudAnnouncementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HudAnnouncementDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HudAnnouncementDefaultTypeInternal() {}
  union {
    HudAnnouncement _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT MODLOCK_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HudAnnouncementDefaultTypeInternal _HudAnnouncement_default_instance_;
}  // namespace engine
}  // namespace modlock
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudTextMessage, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudTextMessage, _impl_.dest_),
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudTextMessage, _impl_.param_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudAnnouncement, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudAnnouncement, _impl_.title_locstring_),
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudAnnouncement, _impl_.description_locstring_),
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudAnnouncement, _impl_.classname_),
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudAnnouncement, _impl_.dialog_variable_name_),
        PROTOBUF_FIELD_OFFSET(::modlock::engine::HudAnnouncement, _impl_.dialog_variable_locstring_),
        3,
        4,
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::modlock::engine::HudTextMessage)},
        {7, sizeof(::modlock::engine::HudAnnouncement)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::modlock::engine::_HudTextMessage_default_instance_._instance,
    &::modlock::engine::_HudAnnouncement_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n2github.com/paralin/modlock/proto/modlo"
    "ck/hud.proto\022\016modlock.engine\"-\n\016HudTextM"
    "essage\022\014\n\004dest\030\001 \001(\r\022\r\n\005param\030\002 \003(\t\"\235\001\n\017"
    "HudAnnouncement\022\027\n\017title_locstring\030\001 \001(\t"
    "\022\035\n\025description_locstring\030\002 \001(\t\022\021\n\tclass"
    "name\030\003 \003(\t\022\034\n\024dialog_variable_name\030\004 \003(\t"
    "\022!\n\031dialog_variable_locstring\030\005 \003(\tB1Z/g"
    "ithub.com/paralin/modlock/proto/modlock/"
    "engine"
};
static ::absl::once_flag descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto = {
    false,
    false,
    326,
    descriptor_table_protodef_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto,
    "github.com/paralin/modlock/proto/modlock/hud.proto",
    &descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto,
    file_level_service_descriptors_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto,
};
namespace modlock {
namespace engine {
// ===================================================================

class HudTextMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HudTextMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HudTextMessage, _impl_._has_bits_);
};

HudTextMessage::HudTextMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HudTextMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:modlock.engine.HudTextMessage)
}
PROTOBUF_NDEBUG_INLINE HudTextMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::modlock::engine::HudTextMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        param_{visibility, arena, from.param_} {}

HudTextMessage::HudTextMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const HudTextMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HudTextMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HudTextMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.dest_ = from._impl_.dest_;

  // @@protoc_insertion_point(copy_constructor:modlock.engine.HudTextMessage)
}
PROTOBUF_NDEBUG_INLINE HudTextMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        param_{visibility, arena} {}

inline void HudTextMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.dest_ = {};
}
HudTextMessage::~HudTextMessage() {
  // @@protoc_insertion_point(destructor:modlock.engine.HudTextMessage)
  SharedDtor(*this);
}
inline void HudTextMessage::SharedDtor(MessageLite& self) {
  HudTextMessage& this_ = static_cast<HudTextMessage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HudTextMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HudTextMessage(arena);
}
constexpr auto HudTextMessage::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(HudTextMessage, _impl_.param_) +
          decltype(HudTextMessage::_impl_.param_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(HudTextMessage), alignof(HudTextMessage), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&HudTextMessage::PlacementNew_,
                                 sizeof(HudTextMessage),
                                 alignof(HudTextMessage));
  }
}
constexpr auto HudTextMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HudTextMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HudTextMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HudTextMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HudTextMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HudTextMessage>(), &HudTextMessage::ByteSizeLong,
              &HudTextMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HudTextMessage, _impl_._cached_size_),
          false,
      },
      &HudTextMessage::kDescriptorMethods,
      &descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HudTextMessage_class_data_ =
        HudTextMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HudTextMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HudTextMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HudTextMessage_class_data_.tc_table);
  return HudTextMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
HudTextMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HudTextMessage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HudTextMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::modlock::engine::HudTextMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string param = 2;
    {::_pbi::TcParser::FastBR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(HudTextMessage, _impl_.param_)}},
    // optional uint32 dest = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HudTextMessage, _impl_.dest_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(HudTextMessage, _impl_.dest_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 dest = 1;
    {PROTOBUF_FIELD_OFFSET(HudTextMessage, _impl_.dest_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated string param = 2;
    {PROTOBUF_FIELD_OFFSET(HudTextMessage, _impl_.param_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void HudTextMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:modlock.engine.HudTextMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.param_.Clear();
  }
  _impl_.dest_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HudTextMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HudTextMessage& this_ = static_cast<const HudTextMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HudTextMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HudTextMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:modlock.engine.HudTextMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 dest = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_dest(), target);
  }

  // repeated string param = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_param_size(); i < n; ++i) {
      const auto& s = this_._internal_param().Get(i);
      target = stream->WriteString(2, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:modlock.engine.HudTextMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HudTextMessage::ByteSizeLong(const MessageLite& base) {
  const HudTextMessage& this_ = static_cast<const HudTextMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HudTextMessage::ByteSizeLong() const {
  const HudTextMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:modlock.engine.HudTextMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated string param = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_param().size());
      for (int i = 0, n = this_._internal_param().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_param().Get(i));
      }
    }
    // optional uint32 dest = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_dest());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HudTextMessage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<HudTextMessage*>(&to_msg);
  auto& from = static_cast<const HudTextMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:modlock.engine.HudTextMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_param()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_param());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.dest_ = from._impl_.dest_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void HudTextMessage::CopyFrom(const HudTextMessage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:modlock.engine.HudTextMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HudTextMessage::InternalSwap(HudTextMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.param_.InternalSwap(&other->_impl_.param_);
  swap(_impl_.dest_, other->_impl_.dest_);
}

::google::protobuf::Metadata HudTextMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HudAnnouncement::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HudAnnouncement>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_._has_bits_);
};

HudAnnouncement::HudAnnouncement(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HudAnnouncement_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:modlock.engine.HudAnnouncement)
}
PROTOBUF_NDEBUG_INLINE HudAnnouncement::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::modlock::engine::HudAnnouncement& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        classname_{visibility, arena, from.classname_},
        dialog_variable_name_{visibility, arena, from.dialog_variable_name_},
        dialog_variable_locstring_{visibility, arena, from.dialog_variable_locstring_},
        title_locstring_(arena, from.title_locstring_),
        description_locstring_(arena, from.description_locstring_) {}

HudAnnouncement::HudAnnouncement(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const HudAnnouncement& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HudAnnouncement_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HudAnnouncement* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:modlock.engine.HudAnnouncement)
}
PROTOBUF_NDEBUG_INLINE HudAnnouncement::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        classname_{visibility, arena},
        dialog_variable_name_{visibility, arena},
        dialog_variable_locstring_{visibility, arena},
        title_locstring_(arena),
        description_locstring_(arena) {}

inline void HudAnnouncement::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
HudAnnouncement::~HudAnnouncement() {
  // @@protoc_insertion_point(destructor:modlock.engine.HudAnnouncement)
  SharedDtor(*this);
}
inline void HudAnnouncement::SharedDtor(MessageLite& self) {
  HudAnnouncement& this_ = static_cast<HudAnnouncement&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.title_locstring_.Destroy();
  this_._impl_.description_locstring_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HudAnnouncement::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HudAnnouncement(arena);
}
constexpr auto HudAnnouncement::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.classname_) +
          decltype(HudAnnouncement::_impl_.classname_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.dialog_variable_name_) +
          decltype(HudAnnouncement::_impl_.dialog_variable_name_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.dialog_variable_locstring_) +
          decltype(HudAnnouncement::_impl_.dialog_variable_locstring_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(HudAnnouncement), alignof(HudAnnouncement), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&HudAnnouncement::PlacementNew_,
                                 sizeof(HudAnnouncement),
                                 alignof(HudAnnouncement));
  }
}
constexpr auto HudAnnouncement::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HudAnnouncement_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HudAnnouncement::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HudAnnouncement>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HudAnnouncement::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HudAnnouncement>(), &HudAnnouncement::ByteSizeLong,
              &HudAnnouncement::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_._cached_size_),
          false,
      },
      &HudAnnouncement::kDescriptorMethods,
      &descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HudAnnouncement_class_data_ =
        HudAnnouncement::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HudAnnouncement::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HudAnnouncement_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HudAnnouncement_class_data_.tc_table);
  return HudAnnouncement_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
HudAnnouncement::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HudAnnouncement_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::modlock::engine::HudAnnouncement>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string title_locstring = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 3, 0,
      PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.title_locstring_)}},
    // optional string description_locstring = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 4, 0,
      PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.description_locstring_)}},
    // repeated string classname = 3;
    {::_pbi::TcParser::FastBR1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.classname_)}},
    // repeated string dialog_variable_name = 4;
    {::_pbi::TcParser::FastBR1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.dialog_variable_name_)}},
    // repeated string dialog_variable_locstring = 5;
    {::_pbi::TcParser::FastBR1,
     {42, 2, 0,
      PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.dialog_variable_locstring_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string title_locstring = 1;
    {PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.title_locstring_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional string description_locstring = 2;
    {PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.description_locstring_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated string classname = 3;
    {PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.classname_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // repeated string dialog_variable_name = 4;
    {PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.dialog_variable_name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // repeated string dialog_variable_locstring = 5;
    {PROTOBUF_FIELD_OFFSET(HudAnnouncement, _impl_.dialog_variable_locstring_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void HudAnnouncement::Clear() {
// @@protoc_insertion_point(message_clear_start:modlock.engine.HudAnnouncement)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.classname_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.dialog_variable_name_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.dialog_variable_locstring_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.title_locstring_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.description_locstring_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HudAnnouncement::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HudAnnouncement& this_ = static_cast<const HudAnnouncement&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HudAnnouncement::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HudAnnouncement& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:modlock.engine.HudAnnouncement)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string title_locstring = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    const ::std::string& _s = this_._internal_title_locstring();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string description_locstring = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    const ::std::string& _s = this_._internal_description_locstring();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // repeated string classname = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_classname_size(); i < n; ++i) {
      const auto& s = this_._internal_classname().Get(i);
      target = stream->WriteString(3, s, target);
    }
  }

  // repeated string dialog_variable_name = 4;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (int i = 0, n = this_._internal_dialog_variable_name_size(); i < n; ++i) {
      const auto& s = this_._internal_dialog_variable_name().Get(i);
      target = stream->WriteString(4, s, target);
    }
  }

  // repeated string dialog_variable_locstring = 5;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    for (int i = 0, n = this_._internal_dialog_variable_locstring_size(); i < n; ++i) {
      const auto& s = this_._internal_dialog_variable_locstring().Get(i);
      target = stream->WriteString(5, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:modlock.engine.HudAnnouncement)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HudAnnouncement::ByteSizeLong(const MessageLite& base) {
  const HudAnnouncement& this_ = static_cast<const HudAnnouncement&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HudAnnouncement::ByteSizeLong() const {
  const HudAnnouncement& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:modlock.engine.HudAnnouncement)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated string classname = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_classname().size());
      for (int i = 0, n = this_._internal_classname().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_classname().Get(i));
      }
    }
    // repeated string dialog_variable_name = 4;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_dialog_variable_name().size());
      for (int i = 0, n = this_._internal_dialog_variable_name().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_dialog_variable_name().Get(i));
      }
    }
    // repeated string dialog_variable_locstring = 5;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_dialog_variable_locstring().size());
      for (int i = 0, n = this_._internal_dialog_variable_locstring().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_dialog_variable_locstring().Get(i));
      }
    }
    // optional string title_locstring = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_title_locstring());
    }
    // optional string description_locstring = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_description_locstring());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HudAnnouncement::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<HudAnnouncement*>(&to_msg);
  auto& from = static_cast<const HudAnnouncement&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:modlock.engine.HudAnnouncement)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_classname()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_classname());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_dialog_variable_name()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_dialog_variable_name());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_dialog_variable_locstring()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_dialog_variable_locstring());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_internal_set_title_locstring(from._internal_title_locstring());
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_internal_set_description_locstring(from._internal_description_locstring());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void HudAnnouncement::CopyFrom(const HudAnnouncement& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:modlock.engine.HudAnnouncement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HudAnnouncement::InternalSwap(HudAnnouncement* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.classname_.InternalSwap(&other->_impl_.classname_);
  _impl_.dialog_variable_name_.InternalSwap(&other->_impl_.dialog_variable_name_);
  _impl_.dialog_variable_locstring_.InternalSwap(&other->_impl_.dialog_variable_locstring_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.title_locstring_, &other->_impl_.title_locstring_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.description_locstring_, &other->_impl_.description_locstring_, arena);
}

::google::protobuf::Metadata HudAnnouncement::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace engine
}  // namespace modlock
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
