//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/paralin/modlock/proto/modlock/hud.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto_2epb_2eh
#define github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto MODLOCK_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct MODLOCK_API TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
MODLOCK_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto;
}  // extern "C"
namespace modlock {
namespace engine {
class HudAnnouncement;
struct HudAnnouncementDefaultTypeInternal;
MODLOCK_API extern HudAnnouncementDefaultTypeInternal _HudAnnouncement_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull HudAnnouncement_class_data_;
class HudTextMessage;
struct HudTextMessageDefaultTypeInternal;
MODLOCK_API extern HudTextMessageDefaultTypeInternal _HudTextMessage_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull HudTextMessage_class_data_;
}  // namespace engine
}  // namespace modlock
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace modlock {
namespace engine {

// ===================================================================


// -------------------------------------------------------------------

class MODLOCK_API HudTextMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.engine.HudTextMessage) */ {
 public:
  inline HudTextMessage() : HudTextMessage(nullptr) {}
  ~HudTextMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HudTextMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HudTextMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HudTextMessage(::google::protobuf::internal::ConstantInitialized);

  inline HudTextMessage(const HudTextMessage& from) : HudTextMessage(nullptr, from) {}
  inline HudTextMessage(HudTextMessage&& from) noexcept
      : HudTextMessage(nullptr, ::std::move(from)) {}
  inline HudTextMessage& operator=(const HudTextMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline HudTextMessage& operator=(HudTextMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HudTextMessage& default_instance() {
    return *reinterpret_cast<const HudTextMessage*>(
        &_HudTextMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(HudTextMessage& a, HudTextMessage& b) { a.Swap(&b); }
  inline void Swap(HudTextMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HudTextMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HudTextMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HudTextMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HudTextMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HudTextMessage& from) { HudTextMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HudTextMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.engine.HudTextMessage"; }

  explicit HudTextMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HudTextMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HudTextMessage& from);
  HudTextMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HudTextMessage&& from) noexcept
      : HudTextMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kParamFieldNumber = 2,
    kDestFieldNumber = 1,
  };
  // repeated string param = 2;
  int param_size() const;
  private:
  int _internal_param_size() const;

  public:
  void clear_param() ;
  const ::std::string& param(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_param(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_param(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_param();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_param(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& param() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_param();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_param() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_param();

  public:
  // optional uint32 dest = 1;
  bool has_dest() const;
  void clear_dest() ;
  ::uint32_t dest() const;
  void set_dest(::uint32_t value);

  private:
  ::uint32_t _internal_dest() const;
  void _internal_set_dest(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:modlock.engine.HudTextMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HudTextMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> param_;
    ::uint32_t dest_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull HudTextMessage_class_data_;
// -------------------------------------------------------------------

class MODLOCK_API HudAnnouncement final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.engine.HudAnnouncement) */ {
 public:
  inline HudAnnouncement() : HudAnnouncement(nullptr) {}
  ~HudAnnouncement() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HudAnnouncement* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HudAnnouncement));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HudAnnouncement(::google::protobuf::internal::ConstantInitialized);

  inline HudAnnouncement(const HudAnnouncement& from) : HudAnnouncement(nullptr, from) {}
  inline HudAnnouncement(HudAnnouncement&& from) noexcept
      : HudAnnouncement(nullptr, ::std::move(from)) {}
  inline HudAnnouncement& operator=(const HudAnnouncement& from) {
    CopyFrom(from);
    return *this;
  }
  inline HudAnnouncement& operator=(HudAnnouncement&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HudAnnouncement& default_instance() {
    return *reinterpret_cast<const HudAnnouncement*>(
        &_HudAnnouncement_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(HudAnnouncement& a, HudAnnouncement& b) { a.Swap(&b); }
  inline void Swap(HudAnnouncement* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HudAnnouncement* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HudAnnouncement* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HudAnnouncement>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HudAnnouncement& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HudAnnouncement& from) { HudAnnouncement::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HudAnnouncement* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.engine.HudAnnouncement"; }

  explicit HudAnnouncement(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HudAnnouncement(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HudAnnouncement& from);
  HudAnnouncement(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HudAnnouncement&& from) noexcept
      : HudAnnouncement(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClassnameFieldNumber = 3,
    kDialogVariableNameFieldNumber = 4,
    kDialogVariableLocstringFieldNumber = 5,
    kTitleLocstringFieldNumber = 1,
    kDescriptionLocstringFieldNumber = 2,
  };
  // repeated string classname = 3;
  int classname_size() const;
  private:
  int _internal_classname_size() const;

  public:
  void clear_classname() ;
  const ::std::string& classname(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_classname(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_classname(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_classname();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_classname(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& classname() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_classname();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_classname() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_classname();

  public:
  // repeated string dialog_variable_name = 4;
  int dialog_variable_name_size() const;
  private:
  int _internal_dialog_variable_name_size() const;

  public:
  void clear_dialog_variable_name() ;
  const ::std::string& dialog_variable_name(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_dialog_variable_name(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dialog_variable_name(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_dialog_variable_name();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_dialog_variable_name(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& dialog_variable_name() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_dialog_variable_name();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_dialog_variable_name() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_dialog_variable_name();

  public:
  // repeated string dialog_variable_locstring = 5;
  int dialog_variable_locstring_size() const;
  private:
  int _internal_dialog_variable_locstring_size() const;

  public:
  void clear_dialog_variable_locstring() ;
  const ::std::string& dialog_variable_locstring(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_dialog_variable_locstring(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dialog_variable_locstring(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_dialog_variable_locstring();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_dialog_variable_locstring(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& dialog_variable_locstring() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_dialog_variable_locstring();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_dialog_variable_locstring() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_dialog_variable_locstring();

  public:
  // optional string title_locstring = 1;
  bool has_title_locstring() const;
  void clear_title_locstring() ;
  const ::std::string& title_locstring() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_title_locstring(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_title_locstring();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_title_locstring();
  void set_allocated_title_locstring(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_title_locstring() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_title_locstring(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_title_locstring();

  public:
  // optional string description_locstring = 2;
  bool has_description_locstring() const;
  void clear_description_locstring() ;
  const ::std::string& description_locstring() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_description_locstring(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_description_locstring();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_description_locstring();
  void set_allocated_description_locstring(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_description_locstring() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_description_locstring(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_description_locstring();

  public:
  // @@protoc_insertion_point(class_scope:modlock.engine.HudAnnouncement)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HudAnnouncement& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> classname_;
    ::google::protobuf::RepeatedPtrField<::std::string> dialog_variable_name_;
    ::google::protobuf::RepeatedPtrField<::std::string> dialog_variable_locstring_;
    ::google::protobuf::internal::ArenaStringPtr title_locstring_;
    ::google::protobuf::internal::ArenaStringPtr description_locstring_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull HudAnnouncement_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HudTextMessage

// optional uint32 dest = 1;
inline bool HudTextMessage::has_dest() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void HudTextMessage::clear_dest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t HudTextMessage::dest() const {
  // @@protoc_insertion_point(field_get:modlock.engine.HudTextMessage.dest)
  return _internal_dest();
}
inline void HudTextMessage::set_dest(::uint32_t value) {
  _internal_set_dest(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:modlock.engine.HudTextMessage.dest)
}
inline ::uint32_t HudTextMessage::_internal_dest() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dest_;
}
inline void HudTextMessage::_internal_set_dest(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_ = value;
}

// repeated string param = 2;
inline int HudTextMessage::_internal_param_size() const {
  return _internal_param().size();
}
inline int HudTextMessage::param_size() const {
  return _internal_param_size();
}
inline void HudTextMessage::clear_param() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.param_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL HudTextMessage::add_param()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_param()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:modlock.engine.HudTextMessage.param)
  return _s;
}
inline const ::std::string& HudTextMessage::param(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.HudTextMessage.param)
  return _internal_param().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL HudTextMessage::mutable_param(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:modlock.engine.HudTextMessage.param)
  return _internal_mutable_param()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void HudTextMessage::set_param(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_param()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:modlock.engine.HudTextMessage.param)
}
template <typename Arg_, typename... Args_>
inline void HudTextMessage::add_param(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_param(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:modlock.engine.HudTextMessage.param)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& HudTextMessage::param()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:modlock.engine.HudTextMessage.param)
  return _internal_param();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
HudTextMessage::mutable_param() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:modlock.engine.HudTextMessage.param)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_param();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
HudTextMessage::_internal_param() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.param_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
HudTextMessage::_internal_mutable_param() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.param_;
}

// -------------------------------------------------------------------

// HudAnnouncement

// optional string title_locstring = 1;
inline bool HudAnnouncement::has_title_locstring() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void HudAnnouncement::clear_title_locstring() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_locstring_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& HudAnnouncement::title_locstring() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.HudAnnouncement.title_locstring)
  return _internal_title_locstring();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HudAnnouncement::set_title_locstring(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.title_locstring_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.engine.HudAnnouncement.title_locstring)
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::mutable_title_locstring()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_title_locstring();
  // @@protoc_insertion_point(field_mutable:modlock.engine.HudAnnouncement.title_locstring)
  return _s;
}
inline const ::std::string& HudAnnouncement::_internal_title_locstring() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.title_locstring_.Get();
}
inline void HudAnnouncement::_internal_set_title_locstring(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_locstring_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::_internal_mutable_title_locstring() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.title_locstring_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HudAnnouncement::release_title_locstring() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.engine.HudAnnouncement.title_locstring)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.title_locstring_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.title_locstring_.Set("", GetArena());
  }
  return released;
}
inline void HudAnnouncement::set_allocated_title_locstring(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.title_locstring_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.title_locstring_.IsDefault()) {
    _impl_.title_locstring_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.engine.HudAnnouncement.title_locstring)
}

// optional string description_locstring = 2;
inline bool HudAnnouncement::has_description_locstring() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void HudAnnouncement::clear_description_locstring() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.description_locstring_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& HudAnnouncement::description_locstring() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.HudAnnouncement.description_locstring)
  return _internal_description_locstring();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HudAnnouncement::set_description_locstring(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.description_locstring_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.engine.HudAnnouncement.description_locstring)
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::mutable_description_locstring()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_description_locstring();
  // @@protoc_insertion_point(field_mutable:modlock.engine.HudAnnouncement.description_locstring)
  return _s;
}
inline const ::std::string& HudAnnouncement::_internal_description_locstring() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.description_locstring_.Get();
}
inline void HudAnnouncement::_internal_set_description_locstring(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.description_locstring_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::_internal_mutable_description_locstring() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.description_locstring_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HudAnnouncement::release_description_locstring() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.engine.HudAnnouncement.description_locstring)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.description_locstring_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.description_locstring_.Set("", GetArena());
  }
  return released;
}
inline void HudAnnouncement::set_allocated_description_locstring(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.description_locstring_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.description_locstring_.IsDefault()) {
    _impl_.description_locstring_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.engine.HudAnnouncement.description_locstring)
}

// repeated string classname = 3;
inline int HudAnnouncement::_internal_classname_size() const {
  return _internal_classname().size();
}
inline int HudAnnouncement::classname_size() const {
  return _internal_classname_size();
}
inline void HudAnnouncement::clear_classname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.classname_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::add_classname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_classname()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:modlock.engine.HudAnnouncement.classname)
  return _s;
}
inline const ::std::string& HudAnnouncement::classname(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.HudAnnouncement.classname)
  return _internal_classname().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::mutable_classname(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:modlock.engine.HudAnnouncement.classname)
  return _internal_mutable_classname()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void HudAnnouncement::set_classname(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_classname()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:modlock.engine.HudAnnouncement.classname)
}
template <typename Arg_, typename... Args_>
inline void HudAnnouncement::add_classname(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_classname(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:modlock.engine.HudAnnouncement.classname)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& HudAnnouncement::classname()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:modlock.engine.HudAnnouncement.classname)
  return _internal_classname();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
HudAnnouncement::mutable_classname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:modlock.engine.HudAnnouncement.classname)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_classname();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
HudAnnouncement::_internal_classname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.classname_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
HudAnnouncement::_internal_mutable_classname() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.classname_;
}

// repeated string dialog_variable_name = 4;
inline int HudAnnouncement::_internal_dialog_variable_name_size() const {
  return _internal_dialog_variable_name().size();
}
inline int HudAnnouncement::dialog_variable_name_size() const {
  return _internal_dialog_variable_name_size();
}
inline void HudAnnouncement::clear_dialog_variable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dialog_variable_name_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::add_dialog_variable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_dialog_variable_name()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add_mutable:modlock.engine.HudAnnouncement.dialog_variable_name)
  return _s;
}
inline const ::std::string& HudAnnouncement::dialog_variable_name(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.HudAnnouncement.dialog_variable_name)
  return _internal_dialog_variable_name().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::mutable_dialog_variable_name(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:modlock.engine.HudAnnouncement.dialog_variable_name)
  return _internal_mutable_dialog_variable_name()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void HudAnnouncement::set_dialog_variable_name(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_dialog_variable_name()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:modlock.engine.HudAnnouncement.dialog_variable_name)
}
template <typename Arg_, typename... Args_>
inline void HudAnnouncement::add_dialog_variable_name(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_dialog_variable_name(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:modlock.engine.HudAnnouncement.dialog_variable_name)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& HudAnnouncement::dialog_variable_name()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:modlock.engine.HudAnnouncement.dialog_variable_name)
  return _internal_dialog_variable_name();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
HudAnnouncement::mutable_dialog_variable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:modlock.engine.HudAnnouncement.dialog_variable_name)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_dialog_variable_name();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
HudAnnouncement::_internal_dialog_variable_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dialog_variable_name_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
HudAnnouncement::_internal_mutable_dialog_variable_name() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.dialog_variable_name_;
}

// repeated string dialog_variable_locstring = 5;
inline int HudAnnouncement::_internal_dialog_variable_locstring_size() const {
  return _internal_dialog_variable_locstring().size();
}
inline int HudAnnouncement::dialog_variable_locstring_size() const {
  return _internal_dialog_variable_locstring_size();
}
inline void HudAnnouncement::clear_dialog_variable_locstring() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dialog_variable_locstring_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::add_dialog_variable_locstring()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_dialog_variable_locstring()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add_mutable:modlock.engine.HudAnnouncement.dialog_variable_locstring)
  return _s;
}
inline const ::std::string& HudAnnouncement::dialog_variable_locstring(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.engine.HudAnnouncement.dialog_variable_locstring)
  return _internal_dialog_variable_locstring().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL HudAnnouncement::mutable_dialog_variable_locstring(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:modlock.engine.HudAnnouncement.dialog_variable_locstring)
  return _internal_mutable_dialog_variable_locstring()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void HudAnnouncement::set_dialog_variable_locstring(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_dialog_variable_locstring()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:modlock.engine.HudAnnouncement.dialog_variable_locstring)
}
template <typename Arg_, typename... Args_>
inline void HudAnnouncement::add_dialog_variable_locstring(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_dialog_variable_locstring(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:modlock.engine.HudAnnouncement.dialog_variable_locstring)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& HudAnnouncement::dialog_variable_locstring()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:modlock.engine.HudAnnouncement.dialog_variable_locstring)
  return _internal_dialog_variable_locstring();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
HudAnnouncement::mutable_dialog_variable_locstring() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:modlock.engine.HudAnnouncement.dialog_variable_locstring)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_dialog_variable_locstring();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
HudAnnouncement::_internal_dialog_variable_locstring() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dialog_variable_locstring_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
HudAnnouncement::_internal_mutable_dialog_variable_locstring() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.dialog_variable_locstring_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace engine
}  // namespace modlock


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fhud_2eproto_2epb_2eh
