// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/paralin/modlock/proto/modlock/hud.proto (package modlock.engine, syntax proto2)
/* eslint-disable */

import type { MessageType } from "@aptre/protobuf-es-lite/message";
import { createMessageType } from "@aptre/protobuf-es-lite/message";
import { ScalarType } from "@aptre/protobuf-es-lite/scalar";
import type { PartialFieldInfo } from "@aptre/protobuf-es-lite/field";

export const protobufPackage = "modlock.engine";

/**
 * HudTextMessage matches native CUserMessageTextMsg, message 124.
 *
 * @generated from message modlock.engine.HudTextMessage
 */
export interface HudTextMessage {
  /**
   * Dest selects the native print destination; 4 is HUD_PRINTCENTER.
   *
   * @generated from field: optional uint32 dest = 1;
   */
  dest?: number;
  /**
   * Param contains the text followed by any native format substitutions.
   *
   * @generated from field: repeated string param = 2;
   */
  param?: string[];

};

export const HudTextMessage: MessageType<HudTextMessage> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.engine.HudTextMessage",
    fields: [
        { no: 1, name: "dest", kind: "scalar", T: ScalarType.UINT32, opt: true },
        { no: 2, name: "param", kind: "scalar", T: ScalarType.STRING, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: false,
});

/**
 * HudAnnouncement matches Deadlock CCitadelUserMsg_HudGameAnnouncement, message 363.
 *
 * @generated from message modlock.engine.HudAnnouncement
 */
export interface HudAnnouncement {
  /**
   * TitleLocstring is the announcement title or localization token.
   *
   * @generated from field: optional string title_locstring = 1;
   */
  titleLocstring?: string;
  /**
   * DescriptionLocstring is the announcement description or localization token.
   *
   * @generated from field: optional string description_locstring = 2;
   */
  descriptionLocstring?: string;
  /**
   * Classname adds existing native announcement style classes.
   *
   * @generated from field: repeated string classname = 3;
   */
  classname?: string[];
  /**
   * DialogVariableName identifies an optional localized substitution.
   *
   * @generated from field: repeated string dialog_variable_name = 4;
   */
  dialogVariableName?: string[];
  /**
   * DialogVariableLocstring supplies the localized substitution.
   *
   * @generated from field: repeated string dialog_variable_locstring = 5;
   */
  dialogVariableLocstring?: string[];

};

export const HudAnnouncement: MessageType<HudAnnouncement> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.engine.HudAnnouncement",
    fields: [
        { no: 1, name: "title_locstring", kind: "scalar", T: ScalarType.STRING, opt: true },
        { no: 2, name: "description_locstring", kind: "scalar", T: ScalarType.STRING, opt: true },
        { no: 3, name: "classname", kind: "scalar", T: ScalarType.STRING, repeated: true },
        { no: 4, name: "dialog_variable_name", kind: "scalar", T: ScalarType.STRING, repeated: true },
        { no: 5, name: "dialog_variable_locstring", kind: "scalar", T: ScalarType.STRING, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: false,
});

