//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/paralin/modlock/proto/modlock/stamina_consumed.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fstamina_5fconsumed_2eproto_2epb_2eh
#define github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fstamina_5fconsumed_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fstamina_5fconsumed_2eproto MODLOCK_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct MODLOCK_API TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fstamina_5fconsumed_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
MODLOCK_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fstamina_5fconsumed_2eproto;
}  // extern "C"
namespace modlock {
namespace engine {
class Damage;
struct DamageDefaultTypeInternal;
MODLOCK_API extern DamageDefaultTypeInternal _Damage_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull Damage_class_data_;
class StaminaConsumed;
struct StaminaConsumedDefaultTypeInternal;
MODLOCK_API extern StaminaConsumedDefaultTypeInternal _StaminaConsumed_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull StaminaConsumed_class_data_;
}  // namespace engine
}  // namespace modlock
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace modlock {
namespace engine {

// ===================================================================


// -------------------------------------------------------------------

class MODLOCK_API StaminaConsumed final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.engine.StaminaConsumed) */ {
 public:
  inline StaminaConsumed() : StaminaConsumed(nullptr) {}
  ~StaminaConsumed() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StaminaConsumed* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StaminaConsumed));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StaminaConsumed(::google::protobuf::internal::ConstantInitialized);

  inline StaminaConsumed(const StaminaConsumed& from) : StaminaConsumed(nullptr, from) {}
  inline StaminaConsumed(StaminaConsumed&& from) noexcept
      : StaminaConsumed(nullptr, ::std::move(from)) {}
  inline StaminaConsumed& operator=(const StaminaConsumed& from) {
    CopyFrom(from);
    return *this;
  }
  inline StaminaConsumed& operator=(StaminaConsumed&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StaminaConsumed& default_instance() {
    return *reinterpret_cast<const StaminaConsumed*>(
        &_StaminaConsumed_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StaminaConsumed& a, StaminaConsumed& b) { a.Swap(&b); }
  inline void Swap(StaminaConsumed* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StaminaConsumed* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StaminaConsumed* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StaminaConsumed>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StaminaConsumed& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StaminaConsumed& from) { StaminaConsumed::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StaminaConsumed* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.engine.StaminaConsumed"; }

  explicit StaminaConsumed(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StaminaConsumed(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StaminaConsumed& from);
  StaminaConsumed(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StaminaConsumed&& from) noexcept
      : StaminaConsumed(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStaminaBeforeFieldNumber = 3,
    kStaminaAfterFieldNumber = 4,
    kStaminaMaxFieldNumber = 6,
    kDrainedFieldNumber = 5,
    kPlaySoundFieldNumber = 8,
    kGametimeFieldNumber = 7,
    kEntindexTargetFieldNumber = 1,
  };
  // optional float stamina_before = 3;
  bool has_stamina_before() const;
  void clear_stamina_before() ;
  float stamina_before() const;
  void set_stamina_before(float value);

  private:
  float _internal_stamina_before() const;
  void _internal_set_stamina_before(float value);

  public:
  // optional float stamina_after = 4;
  bool has_stamina_after() const;
  void clear_stamina_after() ;
  float stamina_after() const;
  void set_stamina_after(float value);

  private:
  float _internal_stamina_after() const;
  void _internal_set_stamina_after(float value);

  public:
  // optional float stamina_max = 6;
  bool has_stamina_max() const;
  void clear_stamina_max() ;
  float stamina_max() const;
  void set_stamina_max(float value);

  private:
  float _internal_stamina_max() const;
  void _internal_set_stamina_max(float value);

  public:
  // optional bool drained = 5;
  bool has_drained() const;
  void clear_drained() ;
  bool drained() const;
  void set_drained(bool value);

  private:
  bool _internal_drained() const;
  void _internal_set_drained(bool value);

  public:
  // optional bool play_sound = 8;
  bool has_play_sound() const;
  void clear_play_sound() ;
  bool play_sound() const;
  void set_play_sound(bool value);

  private:
  bool _internal_play_sound() const;
  void _internal_set_play_sound(bool value);

  public:
  // optional float gametime = 7;
  bool has_gametime() const;
  void clear_gametime() ;
  float gametime() const;
  void set_gametime(float value);

  private:
  float _internal_gametime() const;
  void _internal_set_gametime(float value);

  public:
  // optional int32 entindex_target = 1 [default = -1];
  bool has_entindex_target() const;
  void clear_entindex_target() ;
  ::int32_t entindex_target() const;
  void set_entindex_target(::int32_t value);

  private:
  ::int32_t _internal_entindex_target() const;
  void _internal_set_entindex_target(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:modlock.engine.StaminaConsumed)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StaminaConsumed& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float stamina_before_;
    float stamina_after_;
    float stamina_max_;
    bool drained_;
    bool play_sound_;
    float gametime_;
    ::int32_t entindex_target_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fstamina_5fconsumed_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull StaminaConsumed_class_data_;
// -------------------------------------------------------------------

class MODLOCK_API Damage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.engine.Damage) */ {
 public:
  inline Damage() : Damage(nullptr) {}
  ~Damage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Damage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Damage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Damage(::google::protobuf::internal::ConstantInitialized);

  inline Damage(const Damage& from) : Damage(nullptr, from) {}
  inline Damage(Damage&& from) noexcept
      : Damage(nullptr, ::std::move(from)) {}
  inline Damage& operator=(const Damage& from) {
    CopyFrom(from);
    return *this;
  }
  inline Damage& operator=(Damage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Damage& default_instance() {
    return *reinterpret_cast<const Damage*>(
        &_Damage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Damage& a, Damage& b) { a.Swap(&b); }
  inline void Swap(Damage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Damage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Damage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Damage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Damage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Damage& from) { Damage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Damage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.engine.Damage"; }

  explicit Damage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Damage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Damage& from);
  Damage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Damage&& from) noexcept
      : Damage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDamageFieldNumber = 1,
    kHitgroupIdFieldNumber = 21,
    kServerTickFieldNumber = 29,
    kEntindexVictimFieldNumber = 6,
    kEntindexAttackerFieldNumber = 8,
  };
  // optional int32 damage = 1;
  bool has_damage() const;
  void clear_damage() ;
  ::int32_t damage() const;
  void set_damage(::int32_t value);

  private:
  ::int32_t _internal_damage() const;
  void _internal_set_damage(::int32_t value);

  public:
  // optional int32 hitgroup_id = 21;
  bool has_hitgroup_id() const;
  void clear_hitgroup_id() ;
  ::int32_t hitgroup_id() const;
  void set_hitgroup_id(::int32_t value);

  private:
  ::int32_t _internal_hitgroup_id() const;
  void _internal_set_hitgroup_id(::int32_t value);

  public:
  // optional int32 server_tick = 29;
  bool has_server_tick() const;
  void clear_server_tick() ;
  ::int32_t server_tick() const;
  void set_server_tick(::int32_t value);

  private:
  ::int32_t _internal_server_tick() const;
  void _internal_set_server_tick(::int32_t value);

  public:
  // optional int32 entindex_victim = 6 [default = -1];
  bool has_entindex_victim() const;
  void clear_entindex_victim() ;
  ::int32_t entindex_victim() const;
  void set_entindex_victim(::int32_t value);

  private:
  ::int32_t _internal_entindex_victim() const;
  void _internal_set_entindex_victim(::int32_t value);

  public:
  // optional int32 entindex_attacker = 8 [default = -1];
  bool has_entindex_attacker() const;
  void clear_entindex_attacker() ;
  ::int32_t entindex_attacker() const;
  void set_entindex_attacker(::int32_t value);

  private:
  ::int32_t _internal_entindex_attacker() const;
  void _internal_set_entindex_attacker(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:modlock.engine.Damage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Damage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t damage_;
    ::int32_t hitgroup_id_;
    ::int32_t server_tick_;
    ::int32_t entindex_victim_;
    ::int32_t entindex_attacker_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fstamina_5fconsumed_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull Damage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StaminaConsumed

// optional int32 entindex_target = 1 [default = -1];
inline bool StaminaConsumed::has_entindex_target() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void StaminaConsumed::clear_entindex_target() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entindex_target_ = -1;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t StaminaConsumed::entindex_target() const {
  // @@protoc_insertion_point(field_get:modlock.engine.StaminaConsumed.entindex_target)
  return _internal_entindex_target();
}
inline void StaminaConsumed::set_entindex_target(::int32_t value) {
  _internal_set_entindex_target(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:modlock.engine.StaminaConsumed.entindex_target)
}
inline ::int32_t StaminaConsumed::_internal_entindex_target() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entindex_target_;
}
inline void StaminaConsumed::_internal_set_entindex_target(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entindex_target_ = value;
}

// optional float stamina_before = 3;
inline bool StaminaConsumed::has_stamina_before() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void StaminaConsumed::clear_stamina_before() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stamina_before_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline float StaminaConsumed::stamina_before() const {
  // @@protoc_insertion_point(field_get:modlock.engine.StaminaConsumed.stamina_before)
  return _internal_stamina_before();
}
inline void StaminaConsumed::set_stamina_before(float value) {
  _internal_set_stamina_before(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:modlock.engine.StaminaConsumed.stamina_before)
}
inline float StaminaConsumed::_internal_stamina_before() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stamina_before_;
}
inline void StaminaConsumed::_internal_set_stamina_before(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stamina_before_ = value;
}

// optional float stamina_after = 4;
inline bool StaminaConsumed::has_stamina_after() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void StaminaConsumed::clear_stamina_after() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stamina_after_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline float StaminaConsumed::stamina_after() const {
  // @@protoc_insertion_point(field_get:modlock.engine.StaminaConsumed.stamina_after)
  return _internal_stamina_after();
}
inline void StaminaConsumed::set_stamina_after(float value) {
  _internal_set_stamina_after(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:modlock.engine.StaminaConsumed.stamina_after)
}
inline float StaminaConsumed::_internal_stamina_after() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stamina_after_;
}
inline void StaminaConsumed::_internal_set_stamina_after(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stamina_after_ = value;
}

// optional bool drained = 5;
inline bool StaminaConsumed::has_drained() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void StaminaConsumed::clear_drained() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.drained_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool StaminaConsumed::drained() const {
  // @@protoc_insertion_point(field_get:modlock.engine.StaminaConsumed.drained)
  return _internal_drained();
}
inline void StaminaConsumed::set_drained(bool value) {
  _internal_set_drained(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:modlock.engine.StaminaConsumed.drained)
}
inline bool StaminaConsumed::_internal_drained() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.drained_;
}
inline void StaminaConsumed::_internal_set_drained(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.drained_ = value;
}

// optional float stamina_max = 6;
inline bool StaminaConsumed::has_stamina_max() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void StaminaConsumed::clear_stamina_max() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stamina_max_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline float StaminaConsumed::stamina_max() const {
  // @@protoc_insertion_point(field_get:modlock.engine.StaminaConsumed.stamina_max)
  return _internal_stamina_max();
}
inline void StaminaConsumed::set_stamina_max(float value) {
  _internal_set_stamina_max(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:modlock.engine.StaminaConsumed.stamina_max)
}
inline float StaminaConsumed::_internal_stamina_max() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stamina_max_;
}
inline void StaminaConsumed::_internal_set_stamina_max(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stamina_max_ = value;
}

// optional float gametime = 7;
inline bool StaminaConsumed::has_gametime() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void StaminaConsumed::clear_gametime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gametime_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline float StaminaConsumed::gametime() const {
  // @@protoc_insertion_point(field_get:modlock.engine.StaminaConsumed.gametime)
  return _internal_gametime();
}
inline void StaminaConsumed::set_gametime(float value) {
  _internal_set_gametime(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:modlock.engine.StaminaConsumed.gametime)
}
inline float StaminaConsumed::_internal_gametime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gametime_;
}
inline void StaminaConsumed::_internal_set_gametime(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gametime_ = value;
}

// optional bool play_sound = 8;
inline bool StaminaConsumed::has_play_sound() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void StaminaConsumed::clear_play_sound() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.play_sound_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool StaminaConsumed::play_sound() const {
  // @@protoc_insertion_point(field_get:modlock.engine.StaminaConsumed.play_sound)
  return _internal_play_sound();
}
inline void StaminaConsumed::set_play_sound(bool value) {
  _internal_set_play_sound(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:modlock.engine.StaminaConsumed.play_sound)
}
inline bool StaminaConsumed::_internal_play_sound() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.play_sound_;
}
inline void StaminaConsumed::_internal_set_play_sound(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.play_sound_ = value;
}

// -------------------------------------------------------------------

// Damage

// optional int32 damage = 1;
inline bool Damage::has_damage() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Damage::clear_damage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.damage_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t Damage::damage() const {
  // @@protoc_insertion_point(field_get:modlock.engine.Damage.damage)
  return _internal_damage();
}
inline void Damage::set_damage(::int32_t value) {
  _internal_set_damage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:modlock.engine.Damage.damage)
}
inline ::int32_t Damage::_internal_damage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.damage_;
}
inline void Damage::_internal_set_damage(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.damage_ = value;
}

// optional int32 entindex_victim = 6 [default = -1];
inline bool Damage::has_entindex_victim() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void Damage::clear_entindex_victim() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entindex_victim_ = -1;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t Damage::entindex_victim() const {
  // @@protoc_insertion_point(field_get:modlock.engine.Damage.entindex_victim)
  return _internal_entindex_victim();
}
inline void Damage::set_entindex_victim(::int32_t value) {
  _internal_set_entindex_victim(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:modlock.engine.Damage.entindex_victim)
}
inline ::int32_t Damage::_internal_entindex_victim() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entindex_victim_;
}
inline void Damage::_internal_set_entindex_victim(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entindex_victim_ = value;
}

// optional int32 entindex_attacker = 8 [default = -1];
inline bool Damage::has_entindex_attacker() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void Damage::clear_entindex_attacker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entindex_attacker_ = -1;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t Damage::entindex_attacker() const {
  // @@protoc_insertion_point(field_get:modlock.engine.Damage.entindex_attacker)
  return _internal_entindex_attacker();
}
inline void Damage::set_entindex_attacker(::int32_t value) {
  _internal_set_entindex_attacker(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:modlock.engine.Damage.entindex_attacker)
}
inline ::int32_t Damage::_internal_entindex_attacker() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entindex_attacker_;
}
inline void Damage::_internal_set_entindex_attacker(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entindex_attacker_ = value;
}

// optional int32 hitgroup_id = 21;
inline bool Damage::has_hitgroup_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Damage::clear_hitgroup_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hitgroup_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t Damage::hitgroup_id() const {
  // @@protoc_insertion_point(field_get:modlock.engine.Damage.hitgroup_id)
  return _internal_hitgroup_id();
}
inline void Damage::set_hitgroup_id(::int32_t value) {
  _internal_set_hitgroup_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:modlock.engine.Damage.hitgroup_id)
}
inline ::int32_t Damage::_internal_hitgroup_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hitgroup_id_;
}
inline void Damage::_internal_set_hitgroup_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hitgroup_id_ = value;
}

// optional int32 server_tick = 29;
inline bool Damage::has_server_tick() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Damage::clear_server_tick() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_tick_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t Damage::server_tick() const {
  // @@protoc_insertion_point(field_get:modlock.engine.Damage.server_tick)
  return _internal_server_tick();
}
inline void Damage::set_server_tick(::int32_t value) {
  _internal_set_server_tick(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:modlock.engine.Damage.server_tick)
}
inline ::int32_t Damage::_internal_server_tick() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_tick_;
}
inline void Damage::_internal_set_server_tick(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_tick_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace engine
}  // namespace modlock


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fstamina_5fconsumed_2eproto_2epb_2eh
