// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/paralin/modlock/proto/modlock/wasm.proto (package modlock.wasm, syntax proto3)
/* eslint-disable */

import type { MessageType } from "@aptre/protobuf-es-lite/message";
import { createMessageType } from "@aptre/protobuf-es-lite/message";
import { ScalarType } from "@aptre/protobuf-es-lite/scalar";
import type { PartialFieldInfo } from "@aptre/protobuf-es-lite/field";

export const protobufPackage = "modlock.wasm";

/**
 * StartEvent describes the server the mod starts in.
 *
 * @generated from message modlock.wasm.StartEvent
 */
export interface StartEvent {
  /**
   * Args holds the arguments that follow -- on the host command line.
   *
   * @generated from field: repeated string args = 1;
   */
  args?: string[];
  /**
   * CheckOnly is true when the host checks the mod without starting a game;
   * engine requests then fail.
   *
   * @generated from field: bool check_only = 2;
   */
  checkOnly?: boolean;

};

export const StartEvent: MessageType<StartEvent> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.StartEvent",
    fields: [
        { no: 1, name: "args", kind: "scalar", T: ScalarType.STRING, repeated: true },
        { no: 2, name: "check_only", kind: "scalar", T: ScalarType.BOOL },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * FrameEvent identifies one server frame.
 *
 * @generated from message modlock.wasm.FrameEvent
 */
export interface FrameEvent {
  /**
   * Tick is the server tick, or zero when the clock is unavailable.
   *
   * @generated from field: uint64 tick = 1;
   */
  tick?: bigint;
  /**
   * TimeSeconds is the game clock at this frame, in seconds.
   *
   * @generated from field: double time_seconds = 2;
   */
  timeSeconds?: number;

};

export const FrameEvent: MessageType<FrameEvent> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.FrameEvent",
    fields: [
        { no: 1, name: "tick", kind: "scalar", T: ScalarType.UINT64 },
        { no: 2, name: "time_seconds", kind: "scalar", T: ScalarType.DOUBLE },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * CommandEvent carries one command line from a player: a chat line that starts
 * with a slash, without the slash, or a console command the server received.
 *
 * @generated from message modlock.wasm.CommandEvent
 */
export interface CommandEvent {
  /**
   * Slot identifies the player who typed the command.
   *
   * @generated from field: int32 slot = 1;
   */
  slot?: number;
  /**
   * Line is the complete command line, starting with the command name.
   *
   * @generated from field: string line = 2;
   */
  line?: string;

};

export const CommandEvent: MessageType<CommandEvent> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.CommandEvent",
    fields: [
        { no: 1, name: "slot", kind: "scalar", T: ScalarType.INT32 },
        { no: 2, name: "line", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Event is one engine event the host delivers to a WebAssembly mod through
 * its modlock_event export. A new event is a new body case.
 *
 * @generated from message modlock.wasm.Event
 */
export interface Event {

  /**
   * Body selects the event.
   *
   * @generated from oneof modlock.wasm.Event.body
   */
  body?: {
    value?: undefined,
    case: undefined
  } | {
    /**
     * Start begins the mod's active lifetime, once, before any other event.
     *
     * @generated from field: modlock.wasm.StartEvent start = 1;
     */
    value: StartEvent;
    case: "start";
  } | {
    /**
     * Frame runs once per server frame while the mod asked for frames.
     *
     * @generated from field: modlock.wasm.FrameEvent frame = 2;
     */
    value: FrameEvent;
    case: "frame";
  } | {
    /**
     * Command offers one command a player typed.
     *
     * @generated from field: modlock.wasm.CommandEvent command = 3;
     */
    value: CommandEvent;
    case: "command";
  };

};

export const Event: MessageType<Event> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.Event",
    fields: [
        { no: 1, name: "start", kind: "message", T: () => StartEvent, oneof: "body" },
        { no: 2, name: "frame", kind: "message", T: () => FrameEvent, oneof: "body" },
        { no: 3, name: "command", kind: "message", T: () => CommandEvent, oneof: "body" },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * StartResult declares which events the mod consumes.
 *
 * @generated from message modlock.wasm.StartResult
 */
export interface StartResult {
  /**
   * Frames asks for a FrameEvent every server frame.
   *
   * @generated from field: bool frames = 1;
   */
  frames?: boolean;

};

export const StartResult: MessageType<StartResult> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.StartResult",
    fields: [
        { no: 1, name: "frames", kind: "scalar", T: ScalarType.BOOL },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * CommandResult answers whether the mod handled a command.
 *
 * @generated from message modlock.wasm.CommandResult
 */
export interface CommandResult {
  /**
   * Claimed ends the command's dispatch; the game and later mods do not see it.
   *
   * @generated from field: bool claimed = 1;
   */
  claimed?: boolean;

};

export const CommandResult: MessageType<CommandResult> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.CommandResult",
    fields: [
        { no: 1, name: "claimed", kind: "scalar", T: ScalarType.BOOL },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * EventResult is the mod's answer to one Event. An event with no answer
 * returns an empty result.
 *
 * @generated from message modlock.wasm.EventResult
 */
export interface EventResult {

  /**
   * Body carries the answer for the event case that asks for one.
   *
   * @generated from oneof modlock.wasm.EventResult.body
   */
  body?: {
    value?: undefined,
    case: undefined
  } | {
    /**
     * Start answers a StartEvent.
     *
     * @generated from field: modlock.wasm.StartResult start = 1;
     */
    value: StartResult;
    case: "start";
  } | {
    /**
     * Command answers a CommandEvent.
     *
     * @generated from field: modlock.wasm.CommandResult command = 2;
     */
    value: CommandResult;
    case: "command";
  };

};

export const EventResult: MessageType<EventResult> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.EventResult",
    fields: [
        { no: 1, name: "start", kind: "message", T: () => StartResult, oneof: "body" },
        { no: 2, name: "command", kind: "message", T: () => CommandResult, oneof: "body" },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * LogRequest carries one log line.
 *
 * @generated from message modlock.wasm.LogRequest
 */
export interface LogRequest {
  /**
   * Message is the text to log, without a trailing newline.
   *
   * @generated from field: string message = 1;
   */
  message?: string;

};

export const LogRequest: MessageType<LogRequest> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.LogRequest",
    fields: [
        { no: 1, name: "message", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ServerCommandRequest carries one server console line.
 *
 * @generated from message modlock.wasm.ServerCommandRequest
 */
export interface ServerCommandRequest {
  /**
   * Command is the console line, without a trailing newline.
   *
   * @generated from field: string command = 1;
   */
  command?: string;

};

export const ServerCommandRequest: MessageType<ServerCommandRequest> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.ServerCommandRequest",
    fields: [
        { no: 1, name: "command", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ChatRequest addresses server chat to one player.
 *
 * @generated from message modlock.wasm.ChatRequest
 */
export interface ChatRequest {
  /**
   * Slot identifies the receiving player.
   *
   * @generated from field: int32 slot = 1;
   */
  slot?: number;
  /**
   * Text is the chat line.
   *
   * @generated from field: string text = 2;
   */
  text?: string;

};

export const ChatRequest: MessageType<ChatRequest> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.ChatRequest",
    fields: [
        { no: 1, name: "slot", kind: "scalar", T: ScalarType.INT32 },
        { no: 2, name: "text", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * CenterTextRequest replaces one player's center text.
 *
 * @generated from message modlock.wasm.CenterTextRequest
 */
export interface CenterTextRequest {
  /**
   * Slot identifies the receiving player.
   *
   * @generated from field: int32 slot = 1;
   */
  slot?: number;
  /**
   * Text is the text to show; empty text clears it.
   *
   * @generated from field: string text = 2;
   */
  text?: string;

};

export const CenterTextRequest: MessageType<CenterTextRequest> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.CenterTextRequest",
    fields: [
        { no: 1, name: "slot", kind: "scalar", T: ScalarType.INT32 },
        { no: 2, name: "text", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * HostRequest is one call from a mod to the host through modlock.host_call.
 * A new capability is a new body case.
 *
 * @generated from message modlock.wasm.HostRequest
 */
export interface HostRequest {

  /**
   * Body selects the call.
   *
   * @generated from oneof modlock.wasm.HostRequest.body
   */
  body?: {
    value?: undefined,
    case: undefined
  } | {
    /**
     * Log writes one line to the server log under the mod's name.
     *
     * @generated from field: modlock.wasm.LogRequest log = 1;
     */
    value: LogRequest;
    case: "log";
  } | {
    /**
     * ServerCommand runs one line at the server console.
     *
     * @generated from field: modlock.wasm.ServerCommandRequest server_command = 2;
     */
    value: ServerCommandRequest;
    case: "serverCommand";
  } | {
    /**
     * Chat sends server chat to one player.
     *
     * @generated from field: modlock.wasm.ChatRequest chat = 3;
     */
    value: ChatRequest;
    case: "chat";
  } | {
    /**
     * CenterText shows text in the middle of one player's screen.
     *
     * @generated from field: modlock.wasm.CenterTextRequest center_text = 4;
     */
    value: CenterTextRequest;
    case: "centerText";
  };

};

export const HostRequest: MessageType<HostRequest> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.HostRequest",
    fields: [
        { no: 1, name: "log", kind: "message", T: () => LogRequest, oneof: "body" },
        { no: 2, name: "server_command", kind: "message", T: () => ServerCommandRequest, oneof: "body" },
        { no: 3, name: "chat", kind: "message", T: () => ChatRequest, oneof: "body" },
        { no: 4, name: "center_text", kind: "message", T: () => CenterTextRequest, oneof: "body" },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * HostResponse is the host's answer to one HostRequest.
 *
 * @generated from message modlock.wasm.HostResponse
 */
export interface HostResponse {
  /**
   * Error describes why the call failed, or is empty on success.
   *
   * @generated from field: string error = 1;
   */
  error?: string;

};

export const HostResponse: MessageType<HostResponse> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.wasm.HostResponse",
    fields: [
        { no: 1, name: "error", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

