// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.17.0
// source: github.com/paralin/modlock/proto/modlock/hud.proto

package modlock_engine

import (
	fmt "fmt"
	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	io "io"
	slices "slices"
)

// HudTextMessage matches native CUserMessageTextMsg, message 124.
type HudTextMessage struct {
	unknownFields []byte
	// Dest selects the native print destination; 4 is HUD_PRINTCENTER.
	Dest *uint32 `protobuf:"varint,1,opt,name=dest" json:"dest,omitempty"`
	// Param contains the text followed by any native format substitutions.
	Param []string `protobuf:"bytes,2,rep,name=param" json:"param,omitempty"`
}

func (x *HudTextMessage) Reset() {
	*x = HudTextMessage{}
}

func (*HudTextMessage) ProtoMessage() {}

func (x *HudTextMessage) GetDest() uint32 {
	if x != nil && x.Dest != nil {
		return *x.Dest
	}
	return 0
}

func (x *HudTextMessage) GetParam() []string {
	if x != nil {
		return x.Param
	}
	return nil
}

// HudAnnouncement matches Deadlock CCitadelUserMsg_HudGameAnnouncement, message 363.
type HudAnnouncement struct {
	unknownFields []byte
	// TitleLocstring is the announcement title or localization token.
	TitleLocstring *string `protobuf:"bytes,1,opt,name=title_locstring,json=titleLocstring" json:"titleLocstring,omitempty"`
	// DescriptionLocstring is the announcement description or localization token.
	DescriptionLocstring *string `protobuf:"bytes,2,opt,name=description_locstring,json=descriptionLocstring" json:"descriptionLocstring,omitempty"`
	// Classname adds existing native announcement style classes.
	Classname []string `protobuf:"bytes,3,rep,name=classname" json:"classname,omitempty"`
	// DialogVariableName identifies an optional localized substitution.
	DialogVariableName []string `protobuf:"bytes,4,rep,name=dialog_variable_name,json=dialogVariableName" json:"dialogVariableName,omitempty"`
	// DialogVariableLocstring supplies the localized substitution.
	DialogVariableLocstring []string `protobuf:"bytes,5,rep,name=dialog_variable_locstring,json=dialogVariableLocstring" json:"dialogVariableLocstring,omitempty"`
}

func (x *HudAnnouncement) Reset() {
	*x = HudAnnouncement{}
}

func (*HudAnnouncement) ProtoMessage() {}

func (x *HudAnnouncement) GetTitleLocstring() string {
	if x != nil && x.TitleLocstring != nil {
		return *x.TitleLocstring
	}
	return ""
}

func (x *HudAnnouncement) GetDescriptionLocstring() string {
	if x != nil && x.DescriptionLocstring != nil {
		return *x.DescriptionLocstring
	}
	return ""
}

func (x *HudAnnouncement) GetClassname() []string {
	if x != nil {
		return x.Classname
	}
	return nil
}

func (x *HudAnnouncement) GetDialogVariableName() []string {
	if x != nil {
		return x.DialogVariableName
	}
	return nil
}

func (x *HudAnnouncement) GetDialogVariableLocstring() []string {
	if x != nil {
		return x.DialogVariableLocstring
	}
	return nil
}

func (m *HudTextMessage) CloneVT() *HudTextMessage {
	if m == nil {
		return (*HudTextMessage)(nil)
	}
	r := new(HudTextMessage)
	r.Dest = protobuf_go_lite.ClonePtr(m.Dest)
	r.Param = protobuf_go_lite.CloneSlice(m.Param)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *HudTextMessage) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *HudAnnouncement) CloneVT() *HudAnnouncement {
	if m == nil {
		return (*HudAnnouncement)(nil)
	}
	r := new(HudAnnouncement)
	r.TitleLocstring = protobuf_go_lite.ClonePtr(m.TitleLocstring)
	r.DescriptionLocstring = protobuf_go_lite.ClonePtr(m.DescriptionLocstring)
	r.Classname = protobuf_go_lite.CloneSlice(m.Classname)
	r.DialogVariableName = protobuf_go_lite.CloneSlice(m.DialogVariableName)
	r.DialogVariableLocstring = protobuf_go_lite.CloneSlice(m.DialogVariableLocstring)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *HudAnnouncement) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *HudTextMessage) EqualVT(that *HudTextMessage) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Dest, that.Dest) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.Param, that.Param) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *HudTextMessage) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*HudTextMessage)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *HudAnnouncement) EqualVT(that *HudAnnouncement) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TitleLocstring, that.TitleLocstring) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DescriptionLocstring, that.DescriptionLocstring) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.Classname, that.Classname) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.DialogVariableName, that.DialogVariableName) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.DialogVariableLocstring, that.DialogVariableLocstring) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *HudAnnouncement) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*HudAnnouncement)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *HudTextMessage) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HudTextMessage) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *HudTextMessage) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Param) > 0 {
		for iNdEx := len(m.Param) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.Param[iNdEx])
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Dest != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Dest))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HudAnnouncement) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HudAnnouncement) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *HudAnnouncement) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.DialogVariableLocstring) > 0 {
		for iNdEx := len(m.DialogVariableLocstring) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.DialogVariableLocstring[iNdEx])
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.DialogVariableName) > 0 {
		for iNdEx := len(m.DialogVariableName) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.DialogVariableName[iNdEx])
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Classname) > 0 {
		for iNdEx := len(m.Classname) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.Classname[iNdEx])
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.DescriptionLocstring != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.DescriptionLocstring)
		i--
		dAtA[i] = 0x12
	}
	if m.TitleLocstring != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.TitleLocstring)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HudTextMessage) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.Dest)
	n += protobuf_go_lite.SizeStringSlice(1, m.Param)
	n += len(m.unknownFields)
	return n
}

func (m *HudAnnouncement) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.TitleLocstring)
	n += protobuf_go_lite.SizeStringPtr(1, m.DescriptionLocstring)
	n += protobuf_go_lite.SizeStringSlice(1, m.Classname)
	n += protobuf_go_lite.SizeStringSlice(1, m.DialogVariableName)
	n += protobuf_go_lite.SizeStringSlice(1, m.DialogVariableLocstring)
	n += len(m.unknownFields)
	return n
}

func (x *HudTextMessage) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "HudTextMessage")
	if x.Dest != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "dest")
		protobuf_go_lite.TextWriteUint(&sb, *x.Dest)
	}
	if len(x.Param) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "param")
		for i, v := range x.Param {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *HudTextMessage) String() string {
	return x.MarshalProtoText()
}
func (x *HudAnnouncement) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "HudAnnouncement")
	if x.TitleLocstring != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "title_locstring")
		protobuf_go_lite.TextWriteString(&sb, *x.TitleLocstring)
	}
	if x.DescriptionLocstring != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "description_locstring")
		protobuf_go_lite.TextWriteString(&sb, *x.DescriptionLocstring)
	}
	if len(x.Classname) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "classname")
		for i, v := range x.Classname {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if len(x.DialogVariableName) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "dialog_variable_name")
		for i, v := range x.DialogVariableName {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if len(x.DialogVariableLocstring) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "dialog_variable_locstring")
		for i, v := range x.DialogVariableLocstring {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *HudAnnouncement) String() string {
	return x.MarshalProtoText()
}
func (m *HudTextMessage) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HudTextMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HudTextMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dest", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Dest = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Param", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Param = append(m.Param, v)
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HudAnnouncement) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HudAnnouncement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HudAnnouncement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TitleLocstring", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.TitleLocstring = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DescriptionLocstring", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DescriptionLocstring = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classname", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Classname = append(m.Classname, v)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DialogVariableName", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DialogVariableName = append(m.DialogVariableName, v)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DialogVariableLocstring", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DialogVariableLocstring = append(m.DialogVariableLocstring, v)
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
