// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.17.0
// source: github.com/paralin/modlock/proto/modlock/hud.proto

package modlock_engine

import (
	fmt "fmt"
	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	io "io"
	math "math"
	slices "slices"
	strconv "strconv"
)

// ScreenEffectState matches Deadlock PostProcessingGameStates.
type ScreenEffectState int32

const (
	// SCREEN_EFFECT_STATE_KILLED is the stock death treatment.
	ScreenEffectState_SCREEN_EFFECT_STATE_KILLED ScreenEffectState = 0
	// SCREEN_EFFECT_STATE_BLACK fades the view to black.
	ScreenEffectState_SCREEN_EFFECT_STATE_BLACK ScreenEffectState = 1
	// SCREEN_EFFECT_STATE_DOORMAN_HOTEL_VICTIM is the Doorman hotel treatment.
	ScreenEffectState_SCREEN_EFFECT_STATE_DOORMAN_HOTEL_VICTIM ScreenEffectState = 2
	// SCREEN_EFFECT_STATE_BLINDED is the stock blind treatment.
	ScreenEffectState_SCREEN_EFFECT_STATE_BLINDED ScreenEffectState = 3
	// SCREEN_EFFECT_STATE_DRIFTER_DARKNESS_CASTER is Drifter's darkness view.
	ScreenEffectState_SCREEN_EFFECT_STATE_DRIFTER_DARKNESS_CASTER ScreenEffectState = 4
	// SCREEN_EFFECT_STATE_MATCH_INTRO is the match start treatment.
	ScreenEffectState_SCREEN_EFFECT_STATE_MATCH_INTRO ScreenEffectState = 5
)

// Enum value maps for ScreenEffectState.
var (
	ScreenEffectState_name = map[int32]string{
		0: "SCREEN_EFFECT_STATE_KILLED",
		1: "SCREEN_EFFECT_STATE_BLACK",
		2: "SCREEN_EFFECT_STATE_DOORMAN_HOTEL_VICTIM",
		3: "SCREEN_EFFECT_STATE_BLINDED",
		4: "SCREEN_EFFECT_STATE_DRIFTER_DARKNESS_CASTER",
		5: "SCREEN_EFFECT_STATE_MATCH_INTRO",
	}
	ScreenEffectState_value = map[string]int32{
		"SCREEN_EFFECT_STATE_KILLED":                  0,
		"SCREEN_EFFECT_STATE_BLACK":                   1,
		"SCREEN_EFFECT_STATE_DOORMAN_HOTEL_VICTIM":    2,
		"SCREEN_EFFECT_STATE_BLINDED":                 3,
		"SCREEN_EFFECT_STATE_DRIFTER_DARKNESS_CASTER": 4,
		"SCREEN_EFFECT_STATE_MATCH_INTRO":             5,
	}
)

func (x ScreenEffectState) Enum() *ScreenEffectState {
	p := new(ScreenEffectState)
	*p = x
	return p
}

func (x ScreenEffectState) String() string {
	name, valid := ScreenEffectState_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// HudTextMessage matches native CUserMessageTextMsg, message 124.
type HudTextMessage struct {
	unknownFields []byte
	// Dest selects the native print destination; 4 is HUD_PRINTCENTER.
	Dest *uint32 `protobuf:"varint,1,opt,name=dest" json:"dest,omitempty"`
	// Param contains the text followed by any native format substitutions.
	Param []string `protobuf:"bytes,2,rep,name=param" json:"param,omitempty"`
}

func (x *HudTextMessage) Reset() {
	*x = HudTextMessage{}
}

func (*HudTextMessage) ProtoMessage() {}

func (x *HudTextMessage) GetDest() uint32 {
	if x != nil && x.Dest != nil {
		return *x.Dest
	}
	return 0
}

func (x *HudTextMessage) GetParam() []string {
	if x != nil {
		return x.Param
	}
	return nil
}

// HudAnnouncement matches Deadlock CCitadelUserMsg_HudGameAnnouncement, message 363.
type HudAnnouncement struct {
	unknownFields []byte
	// TitleLocstring is the announcement title or localization token.
	TitleLocstring *string `protobuf:"bytes,1,opt,name=title_locstring,json=titleLocstring" json:"titleLocstring,omitempty"`
	// DescriptionLocstring is the announcement description or localization token.
	DescriptionLocstring *string `protobuf:"bytes,2,opt,name=description_locstring,json=descriptionLocstring" json:"descriptionLocstring,omitempty"`
	// Classname adds existing native announcement style classes.
	Classname []string `protobuf:"bytes,3,rep,name=classname" json:"classname,omitempty"`
	// DialogVariableName identifies an optional localized substitution.
	DialogVariableName []string `protobuf:"bytes,4,rep,name=dialog_variable_name,json=dialogVariableName" json:"dialogVariableName,omitempty"`
	// DialogVariableLocstring supplies the localized substitution.
	DialogVariableLocstring []string `protobuf:"bytes,5,rep,name=dialog_variable_locstring,json=dialogVariableLocstring" json:"dialogVariableLocstring,omitempty"`
}

func (x *HudAnnouncement) Reset() {
	*x = HudAnnouncement{}
}

func (*HudAnnouncement) ProtoMessage() {}

func (x *HudAnnouncement) GetTitleLocstring() string {
	if x != nil && x.TitleLocstring != nil {
		return *x.TitleLocstring
	}
	return ""
}

func (x *HudAnnouncement) GetDescriptionLocstring() string {
	if x != nil && x.DescriptionLocstring != nil {
		return *x.DescriptionLocstring
	}
	return ""
}

func (x *HudAnnouncement) GetClassname() []string {
	if x != nil {
		return x.Classname
	}
	return nil
}

func (x *HudAnnouncement) GetDialogVariableName() []string {
	if x != nil {
		return x.DialogVariableName
	}
	return nil
}

func (x *HudAnnouncement) GetDialogVariableLocstring() []string {
	if x != nil {
		return x.DialogVariableLocstring
	}
	return nil
}

// ScreenEffect matches Deadlock CCitadelUserMsg_PostProcessingAnim, message 332.
// The client ignores the message unless entindex_owner names a live entity.
// Each state keeps a list of running instances, so effects of one state stack.
type ScreenEffect struct {
	unknownFields []byte
	// EntindexOwner is the entity the effect belongs to, normally the
	// recipient's pawn.
	EntindexOwner *int32 `protobuf:"varint,1,opt,name=entindex_owner,json=entindexOwner,def=-1" json:"entindexOwner,omitempty"`
	// ClearAllStates ends every running instance of state instead of starting one.
	ClearAllStates *bool `protobuf:"varint,2,opt,name=clear_all_states,json=clearAllStates" json:"clearAllStates,omitempty"`
	// State selects the stock post-processing resource.
	State *ScreenEffectState `protobuf:"varint,3,opt,name=state" json:"state,omitempty"`
	// Delay, FadeInTime, HoldTime and FadeOutTime are seconds, applied in order.
	Delay       *float32 `protobuf:"fixed32,4,opt,name=delay" json:"delay,omitempty"`
	FadeInTime  *float32 `protobuf:"fixed32,5,opt,name=fade_in_time,json=fadeInTime" json:"fadeInTime,omitempty"`
	HoldTime    *float32 `protobuf:"fixed32,6,opt,name=hold_time,json=holdTime" json:"holdTime,omitempty"`
	FadeOutTime *float32 `protobuf:"fixed32,7,opt,name=fade_out_time,json=fadeOutTime" json:"fadeOutTime,omitempty"`
	// Scale weights the effect; the client stores it with each instance.
	Scale *float32 `protobuf:"fixed32,8,opt,name=scale" json:"scale,omitempty"`
}

// Default values for ScreenEffect fields.
const (
	Default_ScreenEffect_EntindexOwner = int32(-1)
)

func (x *ScreenEffect) Reset() {
	*x = ScreenEffect{}
}

func (*ScreenEffect) ProtoMessage() {}

func (x *ScreenEffect) GetEntindexOwner() int32 {
	if x != nil && x.EntindexOwner != nil {
		return *x.EntindexOwner
	}
	return Default_ScreenEffect_EntindexOwner
}

func (x *ScreenEffect) GetClearAllStates() bool {
	if x != nil && x.ClearAllStates != nil {
		return *x.ClearAllStates
	}
	return false
}

func (x *ScreenEffect) GetState() ScreenEffectState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ScreenEffectState_SCREEN_EFFECT_STATE_KILLED
}

func (x *ScreenEffect) GetDelay() float32 {
	if x != nil && x.Delay != nil {
		return *x.Delay
	}
	return 0
}

func (x *ScreenEffect) GetFadeInTime() float32 {
	if x != nil && x.FadeInTime != nil {
		return *x.FadeInTime
	}
	return 0
}

func (x *ScreenEffect) GetHoldTime() float32 {
	if x != nil && x.HoldTime != nil {
		return *x.HoldTime
	}
	return 0
}

func (x *ScreenEffect) GetFadeOutTime() float32 {
	if x != nil && x.FadeOutTime != nil {
		return *x.FadeOutTime
	}
	return 0
}

func (x *ScreenEffect) GetScale() float32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

func (m *HudTextMessage) CloneVT() *HudTextMessage {
	if m == nil {
		return (*HudTextMessage)(nil)
	}
	r := new(HudTextMessage)
	r.Dest = protobuf_go_lite.ClonePtr(m.Dest)
	r.Param = protobuf_go_lite.CloneSlice(m.Param)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *HudTextMessage) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *HudAnnouncement) CloneVT() *HudAnnouncement {
	if m == nil {
		return (*HudAnnouncement)(nil)
	}
	r := new(HudAnnouncement)
	r.TitleLocstring = protobuf_go_lite.ClonePtr(m.TitleLocstring)
	r.DescriptionLocstring = protobuf_go_lite.ClonePtr(m.DescriptionLocstring)
	r.Classname = protobuf_go_lite.CloneSlice(m.Classname)
	r.DialogVariableName = protobuf_go_lite.CloneSlice(m.DialogVariableName)
	r.DialogVariableLocstring = protobuf_go_lite.CloneSlice(m.DialogVariableLocstring)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *HudAnnouncement) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *ScreenEffect) CloneVT() *ScreenEffect {
	if m == nil {
		return (*ScreenEffect)(nil)
	}
	r := new(ScreenEffect)
	r.EntindexOwner = protobuf_go_lite.ClonePtr(m.EntindexOwner)
	r.ClearAllStates = protobuf_go_lite.ClonePtr(m.ClearAllStates)
	r.State = protobuf_go_lite.ClonePtr(m.State)
	r.Delay = protobuf_go_lite.ClonePtr(m.Delay)
	r.FadeInTime = protobuf_go_lite.ClonePtr(m.FadeInTime)
	r.HoldTime = protobuf_go_lite.ClonePtr(m.HoldTime)
	r.FadeOutTime = protobuf_go_lite.ClonePtr(m.FadeOutTime)
	r.Scale = protobuf_go_lite.ClonePtr(m.Scale)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *ScreenEffect) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *HudTextMessage) EqualVT(that *HudTextMessage) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Dest, that.Dest) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.Param, that.Param) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *HudTextMessage) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*HudTextMessage)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *HudAnnouncement) EqualVT(that *HudAnnouncement) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TitleLocstring, that.TitleLocstring) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DescriptionLocstring, that.DescriptionLocstring) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.Classname, that.Classname) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.DialogVariableName, that.DialogVariableName) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.DialogVariableLocstring, that.DialogVariableLocstring) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *HudAnnouncement) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*HudAnnouncement)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ScreenEffect) EqualVT(that *ScreenEffect) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.EntindexOwner, that.EntindexOwner) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.ClearAllStates, that.ClearAllStates) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.State, that.State) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Delay, that.Delay) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.FadeInTime, that.FadeInTime) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.HoldTime, that.HoldTime) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.FadeOutTime, that.FadeOutTime) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Scale, that.Scale) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ScreenEffect) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ScreenEffect)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *HudTextMessage) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HudTextMessage) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *HudTextMessage) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Param) > 0 {
		for iNdEx := len(m.Param) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.Param[iNdEx])
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Dest != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Dest))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HudAnnouncement) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HudAnnouncement) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *HudAnnouncement) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.DialogVariableLocstring) > 0 {
		for iNdEx := len(m.DialogVariableLocstring) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.DialogVariableLocstring[iNdEx])
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.DialogVariableName) > 0 {
		for iNdEx := len(m.DialogVariableName) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.DialogVariableName[iNdEx])
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Classname) > 0 {
		for iNdEx := len(m.Classname) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.Classname[iNdEx])
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.DescriptionLocstring != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.DescriptionLocstring)
		i--
		dAtA[i] = 0x12
	}
	if m.TitleLocstring != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.TitleLocstring)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ScreenEffect) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScreenEffect) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ScreenEffect) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Scale != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(*m.Scale))))
		i--
		dAtA[i] = 0x45
	}
	if m.FadeOutTime != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(*m.FadeOutTime))))
		i--
		dAtA[i] = 0x3d
	}
	if m.HoldTime != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(*m.HoldTime))))
		i--
		dAtA[i] = 0x35
	}
	if m.FadeInTime != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(*m.FadeInTime))))
		i--
		dAtA[i] = 0x2d
	}
	if m.Delay != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(*m.Delay))))
		i--
		dAtA[i] = 0x25
	}
	if m.State != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.State))
		i--
		dAtA[i] = 0x18
	}
	if m.ClearAllStates != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.ClearAllStates)
		i--
		dAtA[i] = 0x10
	}
	if m.EntindexOwner != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.EntindexOwner))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HudTextMessage) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.Dest)
	n += protobuf_go_lite.SizeStringSlice(1, m.Param)
	n += len(m.unknownFields)
	return n
}

func (m *HudAnnouncement) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.TitleLocstring)
	n += protobuf_go_lite.SizeStringPtr(1, m.DescriptionLocstring)
	n += protobuf_go_lite.SizeStringSlice(1, m.Classname)
	n += protobuf_go_lite.SizeStringSlice(1, m.DialogVariableName)
	n += protobuf_go_lite.SizeStringSlice(1, m.DialogVariableLocstring)
	n += len(m.unknownFields)
	return n
}

func (m *ScreenEffect) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.EntindexOwner)
	n += protobuf_go_lite.SizeBoolPtr(1, m.ClearAllStates)
	n += protobuf_go_lite.SizeVarintPtr(1, m.State)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.Delay)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.FadeInTime)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.HoldTime)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.FadeOutTime)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.Scale)
	n += len(m.unknownFields)
	return n
}

func (x ScreenEffectState) MarshalProtoText() string {
	return x.String()
}
func (x *HudTextMessage) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "HudTextMessage")
	if x.Dest != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "dest")
		protobuf_go_lite.TextWriteUint(&sb, *x.Dest)
	}
	if len(x.Param) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "param")
		for i, v := range x.Param {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *HudTextMessage) String() string {
	return x.MarshalProtoText()
}
func (x *HudAnnouncement) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "HudAnnouncement")
	if x.TitleLocstring != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "title_locstring")
		protobuf_go_lite.TextWriteString(&sb, *x.TitleLocstring)
	}
	if x.DescriptionLocstring != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "description_locstring")
		protobuf_go_lite.TextWriteString(&sb, *x.DescriptionLocstring)
	}
	if len(x.Classname) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "classname")
		for i, v := range x.Classname {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if len(x.DialogVariableName) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "dialog_variable_name")
		for i, v := range x.DialogVariableName {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if len(x.DialogVariableLocstring) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "dialog_variable_locstring")
		for i, v := range x.DialogVariableLocstring {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *HudAnnouncement) String() string {
	return x.MarshalProtoText()
}
func (x *ScreenEffect) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "ScreenEffect")
	if x.EntindexOwner != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "entindex_owner")
		protobuf_go_lite.TextWriteInt(&sb, *x.EntindexOwner)
	}
	if x.ClearAllStates != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "clear_all_states")
		protobuf_go_lite.TextWriteBool(&sb, *x.ClearAllStates)
	}
	if x.State != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "state")
		protobuf_go_lite.TextWriteStringer(&sb, x.State)
	}
	if x.Delay != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "delay")
		protobuf_go_lite.TextWriteFloat32(&sb, *x.Delay)
	}
	if x.FadeInTime != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "fade_in_time")
		protobuf_go_lite.TextWriteFloat32(&sb, *x.FadeInTime)
	}
	if x.HoldTime != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "hold_time")
		protobuf_go_lite.TextWriteFloat32(&sb, *x.HoldTime)
	}
	if x.FadeOutTime != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "fade_out_time")
		protobuf_go_lite.TextWriteFloat32(&sb, *x.FadeOutTime)
	}
	if x.Scale != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "scale")
		protobuf_go_lite.TextWriteFloat32(&sb, *x.Scale)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *ScreenEffect) String() string {
	return x.MarshalProtoText()
}
func (m *HudTextMessage) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HudTextMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HudTextMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dest", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Dest = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Param", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Param = append(m.Param, v)
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HudAnnouncement) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HudAnnouncement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HudAnnouncement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TitleLocstring", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.TitleLocstring = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DescriptionLocstring", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DescriptionLocstring = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classname", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Classname = append(m.Classname, v)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DialogVariableName", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DialogVariableName = append(m.DialogVariableName, v)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DialogVariableLocstring", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DialogVariableLocstring = append(m.DialogVariableLocstring, v)
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScreenEffect) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScreenEffect: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScreenEffect: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntindexOwner", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.EntindexOwner = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClearAllStates", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.ClearAllStates = &b
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var v ScreenEffectState
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = ScreenEffectState(_v)
			if err != nil {
				return err
			}
			m.State = &v
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delay", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Delay = &v2
		case 5:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field FadeInTime", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.FadeInTime = &v2
		case 6:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field HoldTime", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.HoldTime = &v2
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field FadeOutTime", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.FadeOutTime = &v2
		case 8:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scale", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Scale = &v2
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
